from typing import Any, Dict, List


def _build_parsing_config(pages: List[int]) -> Dict[str, Any]:
    """Construct the parsing config matching the parse.py settings."""
    parsing_config: Dict[str, Any] = {
        "enhance": {
            "agentic": [
                {"scope": "text"},
                {
                    "scope": "table",
                    "prompt": (
                        "Extract Schedule of Investments tables from SEC N-CSR/N-CSRS. "
                        "Preserve merged headers, multi-line security descriptions, and "
                        "page-spanning tables. Keep numeric columns aligned "
                        "(Principal/Shares, Cost, Fair Value, %Net Assets, Interest Rate, Maturity).\n\n"
                        "PERCENTAGE VALUES:\n"
                        "- Preserve percentages EXACTLY as printed in the document.\n"
                        "- If the document shows '2.78%', extract '2.78%' (do NOT strip the trailing 8).\n"
                        "- Dashes between category names and percentages are SEPARATORS, not minus signs.\n"
                        "- Always include the '%' symbol in percentage values."
                    ),
                },
            ],
            "summarize_figures": False,
        },
        "retrieval": {
            "chunking": {"chunk_mode": "disabled"},
            "filter_blocks": ["Footer", "Page Number"],
            "embedding_optimized": False,
        },
        "formatting": {
            "add_page_markers": True,
            "table_output_format": "html",
            "merge_tables": True,
            "include": [],
        },
        "settings": {
            "ocr_system": "standard",
            "force_url_result": True,
            "persist_results": True,
            "return_images": ["table"],
        },
    }

    if pages:
        min_page = min(pages)
        max_page = max(pages)
        parsing_config["settings"]["page_range"] = {"start": min_page, "end": max_page}

    return parsing_config


def get_extract_config(
    remote_input: str, pages: List[int]
) -> Dict[str, Any]:
    """Create the extract configuration using Reducto SDK settings.
    
    Args:
        remote_input: The remote URL or file reference for the document.
        pages: List of page numbers to extract from.
    """
    parsing_config = _build_parsing_config(pages)

    system_prompt = (
        "You are extracting the Schedule of Investments (SOI) from a U.S. registered "
        "tender offer / interval fund N-CSR or N-CSRS report.\n\n"
        "############################################################\n"
        "############################################################\n"
        "## PRIORITY -1: REJECT ALL TOP HOLDINGS / SUMMARY TABLES ##\n"
        "## (READ THIS FIRST - HIGHEST PRIORITY RULE)             ##\n"
        "############################################################\n"
        "############################################################\n\n"
        "*** ABSOLUTE RULE: NEVER EXTRACT FROM SUMMARY/HIGHLIGHT SECTIONS ***\n"
        "N-CSR documents typically have a 'Highlights' section on the first few pages (1-4)\n"
        "that contains summary tables. These are NOT the Schedule of Investments.\n\n"
        "*** BLACKLISTED TABLE TITLES - SKIP THESE ENTIRELY ***\n"
        "If you see ANY of these titles, DO NOT extract from that table:\n"
        "- 'Largest Investment Holdings'\n"
        "- 'Top Holdings' / 'Top Ten Holdings'\n"
        "- 'Major Investment Holdings'\n"
        "- 'Significant Holdings' / 'Principal Holdings'\n"
        "- 'Investment Highlights' / 'Portfolio Highlights'\n"
        "- 'Major Portfolio Changes'\n"
        "- 'DIVERSIFICATION OF ASSETS'\n"
        "- 'Major Industry Exposure'\n\n"
        "*** CRITICAL: DO NOT SKIP MAIN SOI ROWS BECAUSE THEY APPEARED IN SUMMARY ***\n"
        "A common extraction error is seeing a security name in a 'Top Holdings' summary\n"
        "and then SKIPPING that same security when it appears in the Main SOI.\n"
        "THIS IS WRONG. The summary table is SEPARATE from the Main SOI.\n\n"
        "EXAMPLE OF WRONG BEHAVIOR:\n"
        "  Page 2 (Summary): 'Compania Cervecerias Unidas S.A.' listed as top holding\n"
        "  Page 6 (Main SOI): Same 'Compania Cervecerias Unidas S.A.' appears\n"
        "  WRONG: 'I already saw this in the summary, so I'll skip it'\n"
        "  CORRECT: Extract EVERY row from the Main SOI, regardless of what's in summaries\n\n"
        "*** RULE: EXTRACT EVERY HOLDING FROM THE MAIN SOI ***\n"
        "- The Main SOI is the ONLY authoritative source\n"
        "- Summary tables are for human readers, NOT for extraction\n"
        "- Even if a security appears in both places, ONLY extract from the Main SOI\n"
        "- Do NOT assume 'this was already extracted' - summaries don't count\n\n"
        "*** DETECTION: HOW TO IDENTIFY SUMMARY VS MAIN SOI ***\n"
        "SUMMARY/HIGHLIGHTS (SKIP):\n"
        "- Located on pages 1-4 (usually)\n"
        "- Has 5-15 holdings followed by a Total showing <80% of net assets\n"
        "- Title contains 'Top', 'Largest', 'Major', 'Highlights', 'Diversification'\n"
        "- Shows ONLY Name + Value + % (no maturity dates, no interest rates)\n\n"
        "MAIN SOI (EXTRACT FROM HERE):\n"
        "- Title: 'Schedule of Investments' or 'Portfolio of Investments'\n"
        "- Located after the Highlights section (usually page 5+)\n"
        "- Contains COMPLETE holdings list (not just 'top' ones)\n"
        "- For bonds: Has maturity dates, interest rates, principal amounts\n"
        "- For equities: Has share classes (Class A, ADR, PNA/PNB, Series B)\n"
        "- Total row shows 90-160% of net assets (full portfolio)\n\n"
        "############################################################\n"
        "############################################################\n"
        "## PRIORITY -0.5: MANDATORY FUND NAME VERIFICATION ##\n"
        "## (CHECK THIS BEFORE EMITTING ANY ROW)             ##\n"
        "############################################################\n"
        "############################################################\n\n"
        "*** ABSOLUTE RULE: EVERY HOLDING MUST HAVE A FUND NAME ***\n"
        "In multi-fund documents, the FIRST element of section_path MUST be the fund name.\n"
        "Do NOT emit holdings with strategy-only paths like ['EVENT DRIVEN'] or ['FIXED INCOME ARBITRAGE'].\n\n"
        "*** CRITICAL: STRATEGY CATEGORIES ARE NOT FUND NAMES ***\n"
        "These strategy names are INTERNAL CATEGORIZATIONS, not fund identifiers:\n"
        "- 'EVENT DRIVEN'\n"
        "- 'FIXED INCOME ARBITRAGE'\n"
        "- 'EQUITY ARBITRAGE'\n"
        "- 'CREDIT STRATEGIES'\n"
        "- 'LONG/SHORT EQUITY'\n"
        "- 'MULTI-STRATEGY'\n"
        "- 'CONVERTIBLE ARBITRAGE'\n"
        "- 'DISTRESSED/RESTRUCTURING'\n"
        "- 'MERGER ARBITRAGE'\n"
        "- 'GLOBAL MACRO'\n\n"
        "If you see these at the ROOT level of section_path, you MISSED THE FUND NAME.\n"
        "Look for the ACTUAL fund name in:\n"
        "1. Page headers: 'FCT FUND CAPITAL TRUST - Schedule of Investments'\n"
        "2. Page footers: Often repeat the fund name\n"
        "3. Document title page: Usually lists all fund names\n"
        "4. TOTAL row labels: 'MEMBERS' CAPITAL - FCT' indicates fund name 'FCT'\n\n"
        "*** EXAMPLE: FUND-OF-FUNDS WITH STRATEGY ALLOCATIONS ***\n"
        "Document shows:\n"
        "  FCT Fund Capital Trust\n"
        "  Schedule of Investments\n"
        "    EVENT DRIVEN\n"
        "      Holding A: $1,000,000\n"
        "      Holding B: $2,000,000\n"
        "    FIXED INCOME ARBITRAGE\n"
        "      Holding C: $3,000,000\n"
        "  TOTAL INVESTMENTS: $6,000,000\n"
        "  \n"
        "  Multi-Strategy Series M\n"
        "  Schedule of Investments\n"
        "    EVENT DRIVEN\n"
        "      Holding D: $4,000,000\n"
        "  TOTAL INVESTMENTS: $4,000,000\n\n"
        "WRONG section_paths (strategies at root):\n"
        "  ['EVENT DRIVEN'] <- Missing fund name!\n"
        "  ['FIXED INCOME ARBITRAGE'] <- Missing fund name!\n\n"
        "CORRECT section_paths (fund name first):\n"
        "  ['FCT Fund Capital Trust', 'EVENT DRIVEN']\n"
        "  ['FCT Fund Capital Trust', 'FIXED INCOME ARBITRAGE']\n"
        "  ['Multi-Strategy Series M', 'EVENT DRIVEN']\n\n"
        "*** BEFORE EMITTING ANY HOLDING, ASK: ***\n"
        "1. Is section_path[0] a FUND NAME (not a strategy category)?\n"
        "2. If I see 'EVENT DRIVEN' at root, what fund does it belong to?\n"
        "3. Does the page header/footer show a fund name I should prepend?\n\n"
        "*** ROOT-LEVEL TOTAL VERIFICATION (CRITICAL) ***\n"
        "Before emitting a TOTAL INVESTMENTS row:\n"
        "1. If section_path is [], verify this is a single-fund document\n"
        "2. If you see ANY holdings with fund names in section_path[0], this is multi-fund\n"
        "3. In multi-fund: TOTAL must have section_path = [FUND_NAME], NEVER []\n"
        "4. A [] path TOTAL in multi-fund docs causes validation failures\n\n"
        "*** ARITHMETIC CONSEQUENCE OF MISSING FUND NAMES ***\n"
        "If you extract:\n"
        "  Holdings A, B, C under ['EVENT DRIVEN'] (no fund) = $6M\n"
        "  Holdings D, E under ['Multi-Strategy', 'EVENT DRIVEN'] = $4M\n"
        "  TOTAL INVESTMENTS under [] = $6M (for first fund only)\n\n"
        "The validator will sum ALL holdings ($6M + $4M = $10M)\n"
        "and compare to TOTAL ($6M) -> $4M MISMATCH ERROR!\n\n"
        "FIX: Put fund name in section_path[0] for ALL holdings:\n"
        "  ['FCT', 'EVENT DRIVEN'] for Holdings A, B, C\n"
        "  ['Multi-Strategy', 'EVENT DRIVEN'] for Holdings D, E\n"
        "  ['FCT'] for first TOTAL\n"
        "  ['Multi-Strategy'] for second TOTAL\n\n"
        "============================================================\n"
        "PRIORITY 0: FIND THE CORRECT TABLE FIRST (CRITICAL)\n"
        "============================================================\n\n"
        "*** DOCUMENT STRUCTURE - WHERE TO EXTRACT FROM ***\n"
        "N-CSR documents typically have this structure:\n"
        "1. Cover page, Table of Contents\n"
        "2. Letter to Shareholders (narrative text)\n"
        "3. HIGHLIGHTS SECTION (pages 2-4) - DO NOT EXTRACT FROM HERE:\n"
        "   - 'Largest Investment Holdings' or 'Top Holdings' table\n"
        "   - 'Major Portfolio Changes' table\n"
        "   - 'Major Industry Exposure' chart\n"
        "   - 'DIVERSIFICATION OF ASSETS' summary table\n"
        "4. THE MAIN SCHEDULE OF INVESTMENTS (pages 5+) - EXTRACT FROM HERE:\n"
        "   - Title: 'Portfolio of Investments' or 'Schedule of Investments'\n"
        "   - Contains INDIVIDUAL securities with issuer names and bond details\n"
        "   - Organized by asset class: 'CONVERTIBLE BONDS', 'PREFERRED STOCKS', etc.\n"
        "   - Has industry subcategories: 'Aerospace', 'Banking', 'Technology', etc.\n"
        "5. Financial Statements (after the SOI)\n\n"
        "*** CRITICAL: START EXTRACTION AT THE MAIN SCHEDULE ***\n"
        "- SKIP all 'Highlights', 'Top Holdings', 'Diversification' tables\n"
        "- FIND the title 'Portfolio of Investments' or 'Schedule of Investments'\n"
        "- ONLY extract from that section forward\n"
        "- The main SOI has INDIVIDUAL SECURITIES (company names, bond terms)\n"
        "- Summary tables only have CATEGORY NAMES (Aerospace, Banking, etc.)\n\n"
        "*** CRITICAL RULE: COMMON ISSUER WITH MULTIPLE ISSUES ***\n"
        "Often an issuer name appears once, followed by multiple indented lines for specific issues:\n"
        "  Federal National Mortgage Association,\n"
        "    2.125%, 10/09/07 ........................ 4,020,000,000 JPY    $ 34,871,099\n"
        "    1.75%, 3/26/08 ..........................   660,000,000 JPY       5,727,731\n\n"
        "YOU MUST EXTRACT EACH INDENTED LINE AS A SEPARATE HOLDING.\n"
        "- Row 1: investment='Federal National Mortgage Association 2.125% 10/09/07'\n"
        "- Row 2: investment='Federal National Mortgage Association 1.75% 3/26/08'\n"
        "  (Distribute the parent issuer name to ALL indented children)\n"
        "- DO NOT merge them into one holding.\n"
        "- DO NOT skip the second line because it has no name.\n"
        "- LOOK for the indented structure with numeric columns.\n\n"
        "============================================================\n"
        "PRIORITY 0.5: MULTI-FUND DOCUMENTS (CRITICAL)\n"
        "============================================================\n\n"
        "*** DETECT MULTI-FUND DOCUMENTS ***\n"
        "Many N-CSR filings contain MULTIPLE DISTINCT FUNDS in a single PDF.\n"
        "Each fund has its own complete Schedule of Investments with its own totals.\n\n"
        "*** DETECTION HEURISTICS ***\n"
        "You are in a MULTI-FUND document if you see:\n"
        "1. Multiple 'Schedule of Investments' or 'Portfolio of Investments' titles\n"
        "2. Fund name headers like:\n"
        "   - 'PIMCO NEW YORK MUNICIPAL INCOME FUND II'\n"
        "   - 'PIMCO CALIFORNIA MUNICIPAL INCOME FUND II'\n"
        "   - 'PIMCO Municipal Income Fund II'\n"
        "3. Multiple 'TOTAL INVESTMENTS' rows (one per fund)\n"
        "4. Repeated section structures (Municipal Bonds, Treasury Bills, Call Options)\n\n"
        "*** CRITICAL RULE: FUND NAME MUST BE FIRST IN SECTION_PATH ***\n"
        "When multiple funds exist, the FUND NAME must be the FIRST element of section_path.\n"
        "This separates holdings from different funds and prevents cross-fund arithmetic errors.\n\n"
        "EXAMPLE - Multi-fund document with 3 funds:\n"
        "  Fund 1: 'PIMCO NEW YORK MUNICIPAL INCOME FUND II'\n"
        "  Fund 2: 'PIMCO CALIFORNIA MUNICIPAL INCOME FUND II'\n"
        "  Fund 3: 'PIMCO Municipal Income Fund II'\n\n"
        "CORRECT section_paths:\n"
        "  ['PIMCO NEW YORK MUNICIPAL INCOME FUND II', 'Municipal Bonds & Notes', 'NEW YORK']\n"
        "  ['PIMCO NEW YORK MUNICIPAL INCOME FUND II', 'U.S. TREASURY BILLS']\n"
        "  ['PIMCO CALIFORNIA MUNICIPAL INCOME FUND II', 'Municipal Bonds & Notes', 'CALIFORNIA']\n"
        "  ['PIMCO CALIFORNIA MUNICIPAL INCOME FUND II', 'U.S. TREASURY BILLS']\n\n"
        "WRONG (causes fund totals to be mixed together):\n"
        "  ['Municipal Bonds & Notes', 'NEW YORK']  <-- Missing fund name!\n"
        "  ['U.S. TREASURY BILLS']  <-- Which fund does this belong to?\n\n"
        "*** CONTINUITY OF FUND CONTEXT (CRITICAL) ***\n"
        "If a section starts with an Asset Class title (e.g., 'MUNICIPAL BONDS') but NO Fund Name:\n"
        "- Assume it belongs to the LAST SEEN Fund Name.\n"
        "- Prepend that Fund Name to the section_path.\n"
        "- DO NOT create an orphan root section like ['MUNICIPAL BONDS'].\n"
        "- CORRECT: ['PIMCO NEW YORK...', 'MUNICIPAL BONDS']\n"
        "- WRONG: ['MUNICIPAL BONDS'] (orphaned)\n"
        "- WATCH FOOTERS: Often the Fund Name appears in the footer if not in the header.\n\n"
        "*** FUND BOUNDARIES ***\n"
        "When you see a new fund's Schedule of Investments title:\n"
        "1. RESET section_path completely\n"
        "2. Set the new fund name as the FIRST element\n"
        "3. All subsequent holdings/subtotals/totals belong to this fund\n"
        "4. Continue until you see the NEXT fund's title\n\n"
        "*** EACH FUND HAS ITS OWN TOTAL ***\n"
        "In a multi-fund document:\n"
        "- Each fund has its own 'TOTAL INVESTMENTS' row\n"
        "- This total should sum holdings ONLY from that fund\n"
        "- section_path for the total: [FUND_NAME] (just the fund, no asset class)\n"
        "- Example: ['PIMCO NEW YORK MUNICIPAL INCOME FUND II'] for its total\n"
        "- NEVER emit a Total row with an empty section_path [] in a multi-fund document.\n"
        "- If you see 'TOTAL INVESTMENTS' at the end of Fund A, it belongs to Fund A.\n"
        "  Set section_path=['Fund A']. Do NOT leave it empty.\n\n"
        "*** CRITICAL: MULTI-FUND BOUNDARY DETECTION ***\n"
        "When you see DIFFERENT 'Total Investments' values appearing in succession:\n"
        "  Total Investments (Fund A): $68,761,510\n"
        "  Total Investments (Fund B): $48,503,011\n"
        "These indicate SEPARATE FUNDS. Do NOT sum them together.\n"
        "- Each Total belongs to its respective fund only\n"
        "- The grand total of all holdings should NOT be emitted unless explicitly shown\n"
        "- If you see a combined total at the very end, it should have section_path=[]\n\n"
        "############################################################\n"
        "*** FUND BOUNDARY VERIFICATION (MANDATORY BEFORE TOTAL) ***\n"
        "############################################################\n\n"
        "BEFORE emitting a TOTAL INVESTMENTS row, verify:\n"
        "1. Count distinct fund names in section_paths you've emitted\n"
        "2. If count > 1, you have a MULTI-FUND document\n"
        "3. Each fund's holdings should ONLY sum to that fund's TOTAL\n"
        "4. NEVER emit a root-level [] path TOTAL in a multi-fund document\n"
        "5. If sum(Fund A holdings) != Fund A TOTAL, you MISSED HOLDINGS\n\n"
        "*** FUND NAME EXTRACTION FROM PAGE HEADERS/FOOTERS ***\n"
        "Look for fund names in:\n"
        "1. Page headers: 'MULTI-STRATEGY SERIES M - Schedule of Investments'\n"
        "2. Page footers: Often repeat the fund name (e.g., 'Multi-Strategy Series M')\n"
        "3. Section titles: 'Series M - Fixed Income Arbitrage'\n"
        "4. Fund-specific prefixes: 'FCT', 'Series A', 'Series M', 'Fund II'\n"
        "If you see these patterns, ALWAYS prefix section_path with the fund identifier.\n\n"
        "*** FUND NAME PATTERNS TO RECOGNIZE (CRITICAL) ***\n"
        "These patterns indicate fund names that MUST be in section_path:\n"
        "- Series designations: 'Series A', 'Series B', 'Series M', 'Multi-Strategy Series M'\n"
        "- Fund numbering: 'Fund II', 'Fund III', 'Fund 2', 'Fund 3'\n"
        "- Geographic funds: 'PIMCO NEW YORK MUNICIPAL INCOME FUND II'\n"
        "- Strategy funds: 'ALLIANCEBERNSTEIN GLOBAL HIGH INCOME FUND'\n"
        "- Duration funds: 'LIMITED DURATION INCOME TRUST', 'Franklin Templeton Limited Duration'\n"
        "- Arbitrage funds: 'FIXED INCOME ARBITRAGE', 'EQUITY ARBITRAGE', 'EVENT DRIVEN'\n"
        "- Trust structures: 'THE GABELLI DIVIDEND & INCOME TRUST'\n"
        "- Alliance funds: 'ALLIANCE NATIONAL MUNICIPAL INCOME FUND'\n\n"
        "*** ARITHMETIC SELF-CHECK BEFORE FINAL TOTAL ***\n"
        "Before emitting TOTAL INVESTMENTS, verify:\n"
        "  sum(all HOLDING fair_values in this fund) approximately equals TOTAL fair_value\n"
        "If sum is DOUBLE the total (e.g., $100M sum vs $50M total):\n"
        "  -> You have DUPLICATE holdings from multiple funds mixed together.\n"
        "  -> Go back and ensure each holding has the correct fund prefix in section_path.\n"
        "If sum is HALF the total (e.g., $50M sum vs $100M total):\n"
        "  -> You MISSED an entire fund's holdings or a large section.\n"
        "  -> Check for continuation pages you may have skipped.\n"
        "  -> Look for sections without headers that continue previous pages.\n\n"
        "============================================================\n"
        "PRIORITY 1: COMPLETENESS (MOST CRITICAL)\n"
        "============================================================\n\n"
        "*** ARITHMETIC VALIDATION - DO THIS BEFORE EMITTING ANY TOTAL ROW ***\n"
        "1. Sum all fair_value_raw from HOLDING rows in the section\n"
        "2. Compare to the TOTAL row's fair_value_raw\n"
        "3. If sum < total: YOU MISSED HOLDINGS. Go back and find them.\n"
        "   - Check EVERY page in the section (sections often span 3-5 pages)\n"
        "   - Look for '(continued)' at page tops - these have MORE holdings\n"
        "   - A $1M+ gap means you likely skipped an entire page or block\n"
        "4. Do NOT emit the TOTAL row until your sum matches\n\n"
        "*** PERCENTAGE ANCHOR RULE ***\n"
        "When a section header shows a percentage (e.g., 'CONVERTIBLE BONDS -- 53.6%'):\n"
        "  sum(industry subtotal percentages) MUST equal the section header percentage\n"
        "If your industry percentages sum to less than the header, you MISSED an industry block.\n"
        "Re-scan all pages for the missing industry/category.\n\n"
        "*** NO SKIPPED PAGES ***\n"
        "- Extract holdings from EVERY page in the provided range\n"
        "- Sections often span 3-5 pages. Extract ALL holdings until you see the section's TOTAL\n"
        "- '(continued)' at page top means MORE holdings follow under the same section\n"
        "- A page with 0 holdings extracted is a RED FLAG - re-scan it\n\n"
        "*** STATE-BY-STATE MUNICIPAL BOND SECTIONS (COMMON PATTERN) ***\n"
        "Municipal bond schedules are often organized by STATE with subtotals:\n"
        "  ALABAMA--3.8%\n"
        "    [3-10 holdings for Alabama]\n"
        "    -----------\n"
        "    48,735,412  <-- State subtotal\n"
        "  ALASKA--1.3%\n"
        "    [holdings for Alaska]\n"
        "    ...\n"
        "  CALIFORNIA--5.2%\n"
        "    [holdings for California]\n"
        "\n"
        "CRITICAL RULES FOR STATE SECTIONS:\n"
        "1. EVERY state header (e.g., 'CALIFORNIA--5.2%') starts a new subsection\n"
        "2. Extract ALL holdings between state headers\n"
        "3. The subtotal line (just a number with dashes) belongs to the PRECEDING state\n"
        "4. Set section_path = ['FUND_NAME', 'MUNICIPAL BONDS & NOTES', 'STATE_NAME']\n"
        "5. If holdings sum to less than the state subtotal, YOU MISSED HOLDINGS\n"
        "6. State sections often continue across page breaks - check for '(CONCLUDED)'\n\n"
        "*** PAGE CONTINUATION MARKERS - CRITICAL ***\n"
        "When a section spans multiple pages, look for these markers:\n"
        "- 'ILLINOIS--(CONCLUDED)' means ILLINOIS holdings continue from previous page\n"
        "- The section_path is STILL ['...', 'ILLINOIS'] - same as before the page break\n"
        "- Column headers (Principal Amount, Credit Rating, Value) are repeated but DO NOT\n"
        "  indicate a new section - they are just table header repetition\n"
        "- Extract ALL holdings on the continuation page under the SAME state/section\n"
        "- Do NOT skip holdings just because column headers appear again\n\n"
        "*** MULTI-SUBSECTION SECTIONS SPAN MULTIPLE PAGES ***\n"
        "Sections like 'SHORT-TERM INVESTMENTS' or 'EQUITY SECURITIES' often have:\n"
        "- Subsection A on page N (e.g., 'CHILEAN MUTUAL FUNDS' with its holdings and subtotal)\n"
        "- Subsection B on the SAME PAGE or NEXT PAGE (e.g., 'GRAND CAYMAN' starting immediately after)\n"
        "- The PARENT total ('TOTAL SHORT-TERM INVESTMENTS') appears AFTER all subsections\n\n"
        "DO NOT assume a section is complete when you finish one subsection.\n"
        "SCAN FORWARD to check for sibling subsections before emitting the parent total.\n\n"
        "*** RULE: EXTRACT UNTIL THE TRUE SECTION END ***\n"
        "Sections like 'SHORT TERM INVESTMENTS' often have multiple subsections (e.g., 'U.S. Treasury Bills', 'Foreign Gov').\n"
        "- Do NOT stop at the first subtotal (e.g., 'Total U.S. Treasury Bills').\n"
        "- Continue extracting ALL subsections until you see the 'TOTAL SHORT TERM INVESTMENTS' row\n"
        "  OR the next major asset class header.\n"
        "- Watch out for page breaks splitting a list of countries (e.g. Canada, Egypt... [page break] ... Sweden, Thailand).\n"
        "- Always check the next page for continuations before closing a section.\n\n"
        "============================================================\n"
        "PRIORITY 1.5: INTERMEDIATE SUBTOTALS DO NOT END PARENT SECTIONS (CRITICAL)\n"
        "============================================================\n\n"
        "*** TRAP: STOPPING EARLY AT INTERMEDIATE SUBTOTALS ***\n"
        "A common extraction error is stopping a section when you see a CATEGORY subtotal.\n"
        "Example: 'SHORT-TERM INVESTMENTS' contains multiple geographic/type subsections:\n"
        "  - 'CHILEAN MUTUAL FUNDS-1.48%' with holdings...\n"
        "  - 'TOTAL CHILEAN MUTUAL FUNDS' <-- THIS IS NOT THE END OF SHORT-TERM INVESTMENTS!\n"
        "  - 'GRAND CAYMAN-1.36%' with holdings...  <-- SIBLING SUBSECTION - MUST EXTRACT\n"
        "  - 'TOTAL SHORT-TERM INVESTMENTS' <-- THIS IS THE TRUE SECTION END\n\n"
        "*** CRITICAL RULE: MATCH TOTAL LABELS TO SECTION HEADERS ***\n"
        "When you see a TOTAL row, ask: 'Does this TOTAL label match the SECTION header?'\n"
        "- Section header: 'SHORT-TERM INVESTMENTS-2.84%'\n"
        "- Intermediate total: 'TOTAL CHILEAN MUTUAL FUNDS' <-- Does NOT match 'SHORT-TERM INVESTMENTS'\n"
        "  -> This is a SUBSECTION total, NOT the section end. KEEP EXTRACTING.\n"
        "- True section total: 'TOTAL SHORT-TERM INVESTMENTS' <-- MATCHES 'SHORT-TERM INVESTMENTS'\n"
        "  -> NOW the section is complete.\n\n"
        "*** SIBLING SUBSECTION HEADERS AFTER INTERMEDIATE TOTALS ***\n"
        "After an intermediate total (e.g., 'TOTAL CHILEAN MUTUAL FUNDS'), look for:\n"
        "- New subsection headers with percentages: 'GRAND CAYMAN-1.36%', 'U.S. TREASURY BILLS-0.5%'\n"
        "- These are SIBLING subsections under the same parent (SHORT-TERM INVESTMENTS)\n"
        "- They MUST be extracted with section_path = [PARENT, SIBLING_NAME]\n"
        "  Example: ['SHORT-TERM INVESTMENTS', 'GRAND CAYMAN']\n\n"
        "*** ARITHMETIC CHECK FOR INCOMPLETE SECTIONS ***\n"
        "Before emitting a section TOTAL, verify:\n"
        "  sum(intermediate_subtotals) == section_total\n"
        "If 'TOTAL CHILEAN MUTUAL FUNDS' = $2.56M but 'TOTAL SHORT-TERM INVESTMENTS' = $4.9M:\n"
        "  -> You are MISSING $2.34M of holdings from another subsection!\n"
        "  -> Go back and find the sibling subsection (e.g., 'GRAND CAYMAN').\n\n"
        "*** COMMON INTERMEDIATE SUBTOTAL PATTERNS ***\n"
        "These indicate SUBSECTION totals, NOT section ends:\n"
        "- 'TOTAL CHILEAN MUTUAL FUNDS' under 'SHORT-TERM INVESTMENTS'\n"
        "- 'TOTAL U.S. TREASURY BILLS' under 'SHORT-TERM INVESTMENTS'\n"
        "- 'TOTAL DOMESTIC BONDS' under 'FIXED INCOME SECURITIES'\n"
        "- 'TOTAL [COUNTRY NAME]' under a geographic parent section\n"
        "- 'Total [Industry]' under an asset class like 'CONVERTIBLE BONDS'\n\n"
        "The TRUE section end has the PARENT name: 'TOTAL SHORT-TERM INVESTMENTS', 'TOTAL FIXED INCOME'.\n\n"
        "============================================================\n"
        "PRIORITY 2: VALUE ACCURACY AND NEGATIVE HANDLING\n"
        "============================================================\n\n"
        "*** LIABILITIES AND NEGATIVE VALUES (CRITICAL) ***\n"
        "Some rows represent LIABILITIES, not assets. These MUST have NEGATIVE fair_value:\n"
        "- 'CALL OPTIONS WRITTEN' or 'OPTIONS WRITTEN'\n"
        "- 'PUT OPTIONS WRITTEN'\n"
        "- 'SHORT POSITIONS' or 'SECURITIES SOLD SHORT'\n"
        "- 'LIABILITIES' or 'OTHER LIABILITIES'\n"
        "- Any row where the document shows parentheses around the fair value\n\n"
        "*** PARENTHESES = NEGATIVE ***\n"
        "In financial documents, parentheses around a number indicate NEGATIVE:\n"
        "- '(368,359)' means NEGATIVE $368,359, extract as '-368359'\n"
        "- '(0.03%)' means NEGATIVE 0.03%, extract as '-0.03%'\n\n"
        "*** CALL OPTIONS WRITTEN EXAMPLE ***\n"
        "Document shows:\n"
        "  CALL OPTIONS WRITTEN (h)--(0.0)%\n"
        "  U.S. Treasury Bond Futures:\n"
        "    (575) Strike Price $112, expires 8/27/04    $ (215,625)\n"
        "    (575) Strike Price $113, expires 8/27/04      (152,734)\n"
        "  Total call options written                      (368,359)\n\n"
        "CORRECT extraction:\n"
        "  {row_type: 'HOLDING', fair_value_raw: '-215625', section_path: ['FUND_NAME', 'CALL OPTIONS WRITTEN']}\n"
        "  {row_type: 'HOLDING', fair_value_raw: '-152734', section_path: ['FUND_NAME', 'CALL OPTIONS WRITTEN']}\n"
        "  {row_type: 'SUBTOTAL', fair_value_raw: '-368359', label: 'Total call options written'}\n\n"
        "*** NET TOTAL CALCULATION ***\n"
        "When 'TOTAL INVESTMENTS, NET OF CALL OPTIONS WRITTEN' appears:\n"
        "  Net Total = Gross Investments + Call Options Written (negative)\n"
        "  Example: $1,299,698,800 + (-$368,359) = $1,299,330,441\n\n"
        "If you extract call options as POSITIVE, the net total will be WRONG.\n\n"
        "*** CONTRA-ENTRIES AND LIABILITY DISCLOSURES (CRITICAL) ***\n"
        "Some SOI documents include 'contra-entries' or liability disclosures that are NOT regular holdings:\n"
        "- 'Preferred Stock, at redemption value' (informational disclosure)\n"
        "- 'PREFERRED SHARES' at root level with large negative value\n"
        "- 'Other assets less liabilities' (net asset calculation line)\n"
        "- 'Net unrealized depreciation' (valuation adjustment)\n"
        "- 'Accrued expenses' or 'Payables'\n\n"
        "*** CRITICAL RULE: DO NOT CLASSIFY THESE AS HOLDINGS ***\n"
        "These rows should be extracted as:\n"
        "1. row_type = 'SUBTOTAL' or 'TOTAL' (NOT 'HOLDING')\n"
        "2. section_path = [] (root level) to separate from regular holdings\n"
        "3. Their fair_value may be negative (liabilities) or informational only\n\n"
        "*** DETECTION HEURISTICS ***\n"
        "A row is likely a contra-entry/liability if:\n"
        "- The investment name contains 'redemption value', 'at redemption', 'liabilities'\n"
        "- It has a LARGE negative fair_value (e.g., -$100M+) at root level\n"
        "- The name is generic like 'PREFERRED SHARES' without specific issuer details\n"
        "- It appears AFTER 'TOTAL INVESTMENTS' as an adjustment line\n\n"
        "*** WHY THIS MATTERS ***\n"
        "If you extract 'Preferred Stock, at redemption value' as a HOLDING with fair_value=-$195M:\n"
        "- The validator will SUM it with regular holdings\n"
        "- This causes a $195M arithmetic mismatch\n"
        "- The extraction will fail validation\n\n"
        "CORRECT: Extract as SUBTOTAL at root level, or skip entirely if it's informational.\n\n"
        "*** PRESERVE PERCENTAGES EXACTLY AS PRINTED ***\n"
        "Extract percentage values EXACTLY as they appear in the document.\n"
        "- If the document shows '2.78%', extract '2.78%' - do NOT modify it.\n"
        "- If the document shows '0.98%', extract '0.98%' - the trailing 8 is VALID.\n"
        "- If the document shows '1.38%', extract '1.38%' - this is a legitimate value.\n"
        "- ALWAYS include the '%' sign in percent_net_assets_raw values.\n\n"
        "*** CONSISTENCY CHECK ***\n"
        "Observe the decimal precision used in the document's TOTAL row.\n"
        "- If TOTAL shows 2 decimal places (e.g., '92.45%'), holdings with 2 decimals are correct.\n"
        "- If TOTAL shows 1 decimal place (e.g., '92.4%'), holdings should match that precision.\n"
        "- Do NOT strip trailing digits to 'fix' perceived OCR errors - trust the document.\n\n"
        "*** HEADER SPLITTING ***\n"
        "When a heading contains BOTH name AND percentage (e.g., 'Automotive -- 1.38%'):\n"
        "- label = 'Automotive' (name only, no numbers/dashes)\n"
        "- percent_net_assets_raw = '1.38%' (preserve the value exactly as shown)\n"
        "Dashes between name and percentage are SEPARATORS, not minus signs.\n\n"
        "*** GEOGRAPHIC/TYPE SUBSECTION HEADERS (CRITICAL) ***\n"
        "Many sections have subsections organized by GEOGRAPHY or INSTRUMENT TYPE.\n"
        "These headers often appear as: 'NAME-PERCENT%' (no space around dash)\n"
        "Examples:\n"
        "- 'CHILEAN MUTUAL FUNDS-1.48%' (geographic subsection)\n"
        "- 'GRAND CAYMAN-1.36%' (geographic subsection)\n"
        "- 'U.S. TREASURY BILLS-0.5%' (instrument type subsection)\n"
        "- 'DOMESTIC BONDS-5.2%' (instrument type subsection)\n\n"
        "*** RULE: EACH SUBSECTION HEADER STARTS A NEW SUBSECTION ***\n"
        "When you see 'GRAND CAYMAN-1.36%' after 'TOTAL CHILEAN MUTUAL FUNDS':\n"
        "1. This is a NEW sibling subsection under the same parent\n"
        "2. Update section_path to [PARENT, 'GRAND CAYMAN']\n"
        "3. Extract ALL holdings under this header until you see its subtotal\n"
        "4. Continue until you see the PARENT's total (e.g., 'TOTAL SHORT-TERM INVESTMENTS')\n\n"
        "*** PARENTHESES HANDLING (CRITICAL) ***\n"
        "Parentheses around percentages typically indicate negative values. HOWEVER:\n"
        "- If a percentage is in parentheses (e.g., '(1.59)%' or '(1.59%)') but the Fair Value\n"
        "  is POSITIVE (no parentheses, no minus sign), the parentheses are stylistic/footnote.\n"
        "- RULE: If fair_value_raw is POSITIVE, REMOVE parentheses from percent_net_assets_raw.\n"
        "- OUTPUT FORMAT: The percent_net_assets_raw string must NOT contain '(' or ')' characters\n"
        "  when the fair_value is positive. Strip them during extraction.\n\n"
        "EXAMPLES:\n"
        "  Input: Fair Value = '$7,622,814', Percent = '(1.59)%'\n"
        "  Output: percent_net_assets_raw = '1.59%' (parentheses REMOVED)\n\n"
        "  Input: Fair Value = '$7,622,814', Percent = '(1.59%)'  \n"
        "  Output: percent_net_assets_raw = '1.59%' (parentheses REMOVED)\n\n"
        "  Input: Fair Value = '$(500,000)', Percent = '(0.5)%'\n"
        "  Output: percent_net_assets_raw = '(0.5)%' (both negative, keep parentheses)\n\n"
        "- Only keep parentheses if BOTH fair_value AND percent are negative/parenthesized.\n\n"
        "============================================================\n"
        "PRIORITY 2.5: EMBEDDED VALUES (COST/PRINCIPAL) - CRITICAL\n"
        "============================================================\n\n"
        "*** COST VALUES EMBEDDED IN ROW TEXT ***\n"
        "Many SEC filings embed cost information directly in the label or investment text,\n"
        "rather than in a separate column. You MUST extract these values.\n\n"
        "*** DETECTION PATTERNS ***\n"
        "Scan the 'label' (for SUBTOTAL/TOTAL rows) or 'investment' text for these patterns:\n"
        "- '(Cost $X,XXX,XXX)' or '(Cost: $X,XXX,XXX)'\n"
        "- 'Cost $X,XXX,XXX' or 'Cost: $X,XXX,XXX'\n"
        "- '(Cost $X)' where X is any dollar amount\n\n"
        "*** EXAMPLES FROM REAL DOCUMENTS ***\n"
        "Document text: 'TOTAL CHILEAN MUTUAL FUNDS (Cost $2,554,747)'\n"
        "CORRECT extraction:\n"
        "  {row_type: 'TOTAL', label: 'TOTAL CHILEAN MUTUAL FUNDS', cost_raw: '2554747', ...}\n\n"
        "Document text: 'TOTAL SHORT-TERM INVESTMENTS (Cost $4,895,747)'\n"
        "CORRECT extraction:\n"
        "  {row_type: 'TOTAL', label: 'TOTAL SHORT-TERM INVESTMENTS', cost_raw: '4895747', ...}\n\n"
        "Document text: 'TOTAL INVESTMENTS-99.98% (Cost $107,236,635)'\n"
        "CORRECT extraction:\n"
        "  {row_type: 'TOTAL', label: 'TOTAL INVESTMENTS', cost_raw: '107236635', percent_net_assets_raw: '99.98%', ...}\n\n"
        "*** CRITICAL RULE: PARENTHESES AROUND 'Cost' ARE NOT NEGATIVE ***\n"
        "When you see '(Cost $X)', the parentheses are FORMATTING, not a negative sign.\n"
        "- '(Cost $2,554,747)' means POSITIVE cost of $2,554,747\n"
        "- Extract as cost_raw: '2554747' (positive, no minus sign)\n"
        "- DO NOT confuse '(Cost ...)' with '($2,554,747)' which would be negative fair value\n\n"
        "*** APPLIES TO ALL ROW TYPES ***\n"
        "This pattern appears in:\n"
        "- HOLDING rows: individual security descriptions may include cost\n"
        "- SUBTOTAL rows: category subtotals often show '(Cost $X)'\n"
        "- TOTAL rows: grand totals almost always show '(Cost $X)'\n\n"
        "*** DO NOT LEAVE cost_raw NULL WHEN COST IS VISIBLE ***\n"
        "If the document shows a cost value (in any format), you MUST extract it.\n"
        "A cost_raw of null when the document clearly shows cost = EXTRACTION ERROR.\n"
        "HOWEVER, if individual holdings DO NOT show cost (only Face Amount and Value),\n"
        "but the Total row DOES show '(Cost $...)', then:\n"
        "- Extract cost_raw for the TOTAL row.\n"
        "- Leave cost_raw null for the HOLDING rows.\n"
        "- This is acceptable and expected for some filings.\n\n"
        "*** STRIP '(Cost ...)' FROM THE LABEL ***\n"
        "When extracting embedded cost, remove the '(Cost $X)' portion from the label:\n"
        "- Input: 'TOTAL INVESTMENTS (Cost $107,236,635)'\n"
        "- Output: label = 'TOTAL INVESTMENTS', cost_raw = '107236635'\n"
        "- NOT: label = 'TOTAL INVESTMENTS (Cost $107,236,635)'\n\n"
        "============================================================\n"
        "PRIORITY 3: CORRECT ROW CLASSIFICATION\n"
        "============================================================\n\n"
        "*** THREE ROW TYPES ***\n"
        "1) HOLDING: Individual security with issuer name + at least one numeric value\n"
        "   - investment = security name (company, bond description, fund name)\n"
        "   - label = null\n"
        "   - section_path = [FUND_NAME (if multi-fund), ASSET_CLASS, CATEGORY (if any)]\n\n"
        "2) SUBTOTAL: Industry/category summary (e.g., 'Pharmaceuticals -- 10.2%')\n"
        "   - label = category name only (no percentages in label)\n"
        "   - investment = null\n"
        "   - percent_net_assets_raw = the percentage\n"
        "   - section_path = [FUND_NAME (if multi-fund), ASSET_CLASS, CATEGORY]\n"
        "   - CRITICAL: label MUST NOT start with 'Total' or 'Net Assets'. Those are TOTAL rows.\n\n"
        "3) TOTAL: Grand totals AND Section totals (e.g., 'Total Investments', 'Total Convertible Bonds')\n"
        "   - label = total text as shown (e.g., 'Total Long-Term Municipal Bonds')\n"
        "   - investment = null\n"
        "   - section_path = [FUND_NAME (if multi-fund), ASSET_CLASS] for section totals\n"
        "   - section_path = [FUND_NAME] or [] for fund/grand totals\n"
        "   - CRITICAL: TOTAL rows share the PARENT path. Do NOT create a new child path level for them.\n\n"
        "*** SECTION_PATH MUST REFLECT FULL HIERARCHY ***\n"
        "In multi-fund documents, ALWAYS include the fund name as the first element.\n"
        "In single-fund documents, start with the asset class.\n\n"
        "*** SIBLING RULE - DO NOT NEST ASSET CLASSES ***\n"
        "Major asset classes must be SIBLINGS, not children of each other.\n"
        "- 'MUNICIPAL BONDS' and 'SHORT-TERM INVESTMENTS' are SIBLINGS.\n"
        "- NEVER nest 'MUNICIPAL BONDS' inside 'SHORT-TERM INVESTMENTS'.\n"
        "- If indentation is confusing, rely on the font style/size of headers.\n"
        "- CHECK: If 'Calculated Percent' of a section is >100% (e.g. 150%), you likely nested a sibling inside it.\n\n"
        "*** HIERARCHY RULE - NO DOUBLE COUNTING ***\n"
        "Section headers vs industry subtotals are DIFFERENT hierarchy levels:\n"
        "- 'CONVERTIBLE BONDS -- 53.6%' is an ASSET CLASS header (anchor total)\n"
        "- 'Advertising -- 0.9%', 'Aerospace -- 1.2%' are INDUSTRY subtotals\n"
        "The industry percentages (0.9 + 1.2 + ...) should SUM to the header percentage (53.6%).\n\n"
        "CORRECT: Emit industry-level SUBTOTAL rows. The asset class header % is metadata/anchor only.\n"
        "WRONG: Emitting BOTH the asset class header as SUBTOTAL AND all industry SUBTOTALs.\n"
        "       This causes double-counting: 53.6% + (0.9+1.2+...) = 107%+ for one section!\n\n"
        "*** ABSOLUTE PROHIBITION: NO 'PHANTOM' TOTAL NODES ***\n"
        "Do NOT emit a Section Total (e.g., 'Total Municipal Bonds') as a SUBTOTAL row with a unique path.\n"
        "- WRONG: row_type='SUBTOTAL', label='Total Muni Bonds', section_path=['Muni Bonds', 'Total Muni Bonds']\n"
        "  -> This creates a new child node that gets SUMMED with the siblings, causing ~200% totals.\n"
        "- CORRECT: row_type='TOTAL', label='Total Muni Bonds', section_path=['Muni Bonds']\n"
        "  -> This stays at the parent level and is used for VALIDATION only.\n\n"
        "============================================================\n"
        "PRIORITY 4: REJECT COLUMN HEADERS\n"
        "============================================================\n\n"
        "*** BLACKLISTED STRINGS - NEVER USE AS ENTIRE INVESTMENT NAME ***\n"
        "These column headers are table structure, not data. DO NOT use them as the ENTIRE 'investment' field:\n"
        "  Principal Amount, Value, Value (Note 1), Shares, Cost, Fair Value,\n"
        "  Par Amount, Par Value, Units, Notional, % of Net Assets, Maturity, Rate, Interest Rate\n\n"
        "If 'investment' would BE EXACTLY a blacklisted string, DO NOT emit the row.\n"
        "Numbers adjacent to headers (e.g., 'Value (Note 1): 8,169,847') are OCR artifacts, not holdings.\n\n"
        "*** IMPORTANT: 'Cost' IN A LABEL INDICATES EMBEDDED DATA ***\n"
        "While 'Cost' alone is a blacklisted investment name, when 'Cost' appears WITHIN a label\n"
        "like '(Cost $2,554,747)', it indicates embedded cost data to EXTRACT (see Priority 2.5).\n"
        "- REJECT: investment = 'Cost' (blacklisted column header)\n"
        "- EXTRACT: label = 'TOTAL INVESTMENTS (Cost $107,236,635)' -> cost_raw = '107236635'\n\n"
        "*** VALID INVESTMENT NAME ***\n"
        "Must contain an identifiable issuer (company, fund, government entity) that could be\n"
        "looked up on Bloomberg/EDGAR. Examples:\n"
        "- VALID: 'Apple Inc.', 'Kerr-McGee Corp. 5.25% 2010 cv. sub. deb.', 'U.S. Treasury Notes'\n"
        "- INVALID: 'Principal Amount:', '$1,500,000', '8,169,847'\n\n"
        "If security name is missing, look ABOVE or on the PREVIOUS page. Multi-line descriptions are common.\n\n"
        "============================================================\n"
        "PRIORITY 5: TOTAL ROW SELECTION & PLACEMENT (CRITICAL)\n"
        "============================================================\n\n"
        "*** RULE 1: GLOBAL TOTALS MUST BE AT ROOT/FUND LEVEL ***\n"
        "Lines containing 'TOTAL INVESTMENTS' or 'NET ASSETS' are GLOBAL/FUND totals.\n"
        "They must NEVER appear nested inside a specific asset class section.\n\n"
        "CRITICAL FOR MULTI-FUND DOCS:\n"
        "- If the document contains multiple funds, there is NO 'Global' total for the whole PDF.\n"
        "- 'TOTAL INVESTMENTS' always refers to the SPECIFIC FUND it is listed under.\n"
        "- ALWAYS include the [FUND_NAME] in the section_path for these totals.\n"
        "- BAD: section_path=[] (implies total of all funds)\n"
        "- GOOD: section_path=['PIMCO CALIFORNIA MUNICIPAL INCOME FUND II']\n\n"
        "SPECIFIC GLOBAL TOTAL PATTERNS (Always Root/Fund Level):\n"
        "- 'TOTAL INVESTMENTS' (Final)\n"
        "- 'NET ASSETS'\n"
        "- 'TOTAL INVESTMENTS, NET OF...'\n\n"
        "*** SKIP INTERMEDIATE GLOBAL TOTALS ***\n"
        "Do NOT emit 'Total' lines that are partial sums of the portfolio.\n"
        "SKIP these lines entirely:\n"
        "- 'TOTAL INVESTMENTS BEFORE MONEY MARKET FUND'\n"
        "- 'TOTAL INVESTMENTS BEFORE SHORT TERM INVESTMENTS'\n"
        "- 'TOTAL INVESTMENTS BEFORE CALL OPTIONS'\n"
        "- Any 'TOTAL INVESTMENTS BEFORE...'\n\n"
        "WRONG section_path (nested under asset class):\n"
        "  {row_type: 'TOTAL', label: 'TOTAL INVESTMENTS BEFORE MONEY MARKET FUND',\n"
        "   section_path: ['SHORT TERM INVESTMENTS']}  <-- WRONG! Global total inside Short Term\n\n"
        "CORRECT section_path (at fund/root level):\n"
        "  {row_type: 'TOTAL', label: 'TOTAL INVESTMENTS BEFORE MONEY MARKET FUND',\n"
        "   section_path: ['PIMCO CALIFORNIA FUND']}  <-- Fund level\n"
        "  OR\n"
        "  {row_type: 'TOTAL', label: 'TOTAL INVESTMENTS BEFORE MONEY MARKET FUND',\n"
        "   section_path: []}  <-- Root level\n\n"
        "*** RULE 2: SKIP INTERMEDIATE TOTALS - EMIT ONLY FINAL NET ***\n"
        "Many documents show both GROSS and NET total lines:\n"
        "  'TOTAL INVESTMENTS BEFORE CALL OPTIONS WRITTEN' -- $1,299,698,800 (GROSS)\n"
        "  'CALL OPTIONS WRITTEN' -- $(368,359) (DEDUCTION)\n"
        "  'TOTAL INVESTMENTS, NET OF CALL OPTIONS WRITTEN' -- $1,299,330,441 (NET FINAL)\n\n"
        "RULE: Only emit the FINAL NET total, SKIP the intermediate 'BEFORE' total:\n"
        "- SKIP: 'TOTAL INVESTMENTS BEFORE CALL OPTIONS'\n"
        "- SKIP: 'TOTAL INVESTMENTS BEFORE ...' (any intermediate)\n"
        "- EMIT: 'TOTAL INVESTMENTS, NET OF CALL OPTIONS WRITTEN' (the final net)\n"
        "- EMIT: 'TOTAL INVESTMENTS' (if no adjustments follow)\n\n"
        "WHY: If you emit BOTH the 'BEFORE' and 'NET' totals, validator will see:\n"
        "  Holdings sum + Call Options = NET total (correct)\n"
        "  But you also emitted BEFORE total, causing double-counting\n\n"
        "*** DETECTION: WHICH TOTAL TO EMIT ***\n"
        "Scan ahead when you see 'TOTAL INVESTMENTS BEFORE...':\n"
        "1. Is there a 'CALL OPTIONS WRITTEN' or similar deduction section after it?\n"
        "2. Is there a 'TOTAL INVESTMENTS, NET OF...' line after the deductions?\n"
        "If YES to both: SKIP the 'BEFORE' total, EMIT only the 'NET OF' total.\n"
        "If NO: EMIT the total you see (it's the final one).\n\n"
        "*** RULE 3: ONE TOTAL PER SECTION ***\n"
        "Each section (e.g., 'CONVERTIBLE BONDS AND NOTES') typically has a TOTAL row at the end.\n"
        "- This row MUST be extracted as row_type='TOTAL'.\n"
        "- It must use the SAME section_path as the holdings it summarizes (do NOT append 'Total' to the path).\n"
        "- Example: Holdings are in ['Muni Bonds']. Total row path is ['Muni Bonds'].\n"
        "- NEVER extract a 'Total ...' row as a SUBTOTAL. This causes double-counting.\n\n"
        "Some sections may list the total twice (once detailed, once in recap). Extract it ONLY ONCE (the detailed one).\n\n"
        "*** DETECT RECAP/SUMMARY BLOCKS ***\n"
        "A recap block looks like this (appears AFTER all detailed sections are complete):\n"
        "  TOTAL CONVERTIBLE BONDS AND NOTES -- 55.6% .......... $63,196,000    $63,059,727\n"
        "  TOTAL CONVERTIBLE PREFERRED STOCKS -- 19.3% ......... $21,022,642    $21,853,153\n"
        "  TOTAL MANDATORY CONVERTIBLE SECURITIES -- 18.9% ..... $21,421,924    $21,466,046\n"
        "  TOTAL SHORT-TERM SECURITIES -- 6.0% ................. $ 6,809,726    $ 6,809,692\n"
        "  TOTAL INVESTMENTS -- 99.8% .......................... $112,450,292  $113,188,618\n\n"
        "This is a SUMMARY TABLE that re-lists totals already extracted. DO NOT extract these rows.\n\n"
        "*** RULE: IF YOU ALREADY EMITTED 'TOTAL [SECTION]', DO NOT EMIT IT AGAIN ***\n"
        "- Track which TOTAL rows you have already emitted\n"
        "- If you see the same 'TOTAL [X]' label again in a summary block, SKIP IT\n"
        "- Only emit 'TOTAL INVESTMENTS' once (the final grand total)\n\n"
        "*** DETECTION HEURISTICS ***\n"
        "You are in a recap block if:\n"
        "1. You see multiple 'TOTAL [Section]' lines in rapid succession (3+ within 10 lines)\n"
        "2. These lines appear AFTER the detailed holdings for those sections were already extracted\n"
        "3. The block ends with 'TOTAL INVESTMENTS' or similar grand total\n\n"
        "Extracting recap rows causes DOUBLE-COUNTING: calculated totals will be ~200% of actual.\n\n"
        "============================================================\n"
        "PRIORITY 5.5: REJECT TOP HOLDINGS / HIGHLIGHT TABLES (CRITICAL)\n"
        "============================================================\n\n"
        "*** ABSOLUTE RULE: NEVER EXTRACT FROM SUMMARY/HIGHLIGHT SECTIONS ***\n"
        "N-CSR documents typically have a 'Highlights' section on the first few pages (1-4)\n"
        "that contains summary tables. These are NOT the Schedule of Investments.\n"
        "The main SOI typically starts on page 5 or later, BUT page numbering can be unreliable.\n\n"
        "*** CONTENT SIGNALS OVERRIDE PAGE LOCATION (CRITICAL) ***\n"
        "If you see a table on what you think is 'Page 2' (or low page number) that has DETAILED holdings:\n"
        "- DETAILED = Has Maturity Dates, Interest Rates, Principal Amounts, or specific bond terms.\n"
        "- ACTION: IT IS THE MAIN SCHEDULE. EXTRACT IT.\n"
        "- Do NOT drop it just because the page number seems low.\n"
        "- Summary/Highlight tables NEVER have maturity dates or interest rates.\n\n"
        "*** PAGE LOCATION CHECK ***\n"
        "Before extracting, check content signals FIRST, then page number:\n"
        "- If table has ONLY Name + Value + % (no maturity/rate): It's a Summary. SKIP IT.\n"
        "- If table has Name + Maturity + Rate + Principal: It's the SOI. EXTRACT IT regardless of page number.\n"
        "- If the table is titled 'Largest Investment Holdings' or similar: SKIP IT ENTIRELY\n"
        "- The main SOI has titles like 'Portfolio of Investments' or 'Schedule of Investments'\n\n"
        "*** CRITICAL: DO NOT EXTRACT FROM SUMMARY HIGHLIGHT TABLES ***\n"
        "Many N-CSR documents include a 'Top Holdings' or 'Largest Investment Holdings'\n"
        "summary table BEFORE the main Schedule of Investments. These tables:\n"
        "- Show only 5-15 'top' or 'largest' holdings (not the full portfolio)\n"
        "- Have their own 'Total' row that sums only those highlighted holdings\n"
        "- Often appear on pages 1-4 of the document, before the main SOI\n"
        "- Use titles like:\n"
        "  'Largest Investment Holdings', 'Largest Investment Holdings by underlying common stock',\n"
        "  'Top Ten Holdings', 'Top Holdings', 'Major Investment Holdings',\n"
        "  'Significant Holdings', 'Principal Holdings', 'Leading Holdings',\n"
        "  'Key Holdings', 'Primary Holdings', 'Investment Highlights',\n"
        "  'Portfolio Highlights', 'Major Portfolio Changes'\n\n"
        "*** DETECTION: YOU ARE IN A TOP HOLDINGS TABLE IF ***\n"
        "Check these signals IN ORDER OF RELIABILITY (content first, page number last):\n"
        "1. The table has ONLY 5-15 holdings followed immediately by a Total row (STRONG SIGNAL)\n"
        "2. The Total row shows a percentage LESS THAN 80% (e.g., 22.8%, 35.1%) (STRONGEST SIGNAL)\n"
        "   - A real SOI total is typically 90-160% of net assets (can exceed 100% for leveraged funds)\n"
        "   - If Total is <80%, this is NOT the main schedule - it's a highlights table\n"
        "3. The section header mentions 'Top', 'Largest', 'Major', 'Significant', 'Principal', or 'Key'\n"
        "4. The Total row's fair_value is 5x+ LARGER than the sum of visible holdings\n"
        "   (This happens when the Total reflects the full portfolio, but only top holdings are listed)\n"
        "5. The table appears BEFORE the main 'Schedule of Investments' or 'Portfolio of Investments' title\n"
        "6. You are on pages 1-4 of the document (WEAK SIGNAL - page numbers can be unreliable)\n\n"
        "*** IMPORTANT: CONTENT SIGNALS OVERRIDE PAGE LOCATION ***\n"
        "If a table has detailed bond information (maturity dates, interest rates, principal amounts),\n"
        "it is the MAIN SOI regardless of what page number you think it's on.\n"
        "Page numbers in PDF metadata can be wrong. Trust the CONTENT of the table.\n\n"
        "*** CRITICAL ARITHMETIC CHECK ***\n"
        "BEFORE emitting a TOTAL row, calculate: sum(extracted_holdings_fair_value) vs total_fair_value\n"
        "- If total_fair_value > 2x sum: YOU MISSED HOLDINGS or are in a Top Holdings table\n"
        "- If total_fair_value > 5x sum: YOU ARE DEFINITELY IN A TOP HOLDINGS TABLE - DISCARD ALL\n"
        "- If total_fair_value > 10x sum: CRITICAL ERROR - stop and re-examine the document structure\n\n"
        "*** PERCENTAGE SANITY CHECK - MOST RELIABLE TEST ***\n"
        "If you see a 'Total' row with percent_net_assets_raw < 80%:\n"
        "- This is VERY LIKELY a highlights/summary table, NOT the main SOI\n"
        "- Real SOI totals are typically 90-160% of net assets\n"
        "- DISCARD all rows from this table immediately\n"
        "- Search for the actual 'Schedule of Investments' or 'Portfolio of Investments'\n\n"
        "*** RULE: SKIP ALL ROWS FROM TOP HOLDINGS TABLES ***\n"
        "If you detect you are in a Top Holdings summary table:\n"
        "- DO NOT emit any HOLDING rows from this table\n"
        "- DO NOT emit the Total row from this table\n"
        "- Continue scanning until you find the main SOI ('Schedule of Investments' or 'Portfolio of Investments')\n"
        "- Only extract from the main SOI section\n\n"
        "*** DUPLICATE DETECTION - CRITICAL FOR ARITHMETIC ***\n"
        "If you extract holdings from BOTH a highlights table AND the main SOI:\n"
        "- You will have DUPLICATE holdings (same securities listed twice)\n"
        "- This causes calculated totals to be ~200% of the actual value\n"
        "- This is a CRITICAL ERROR that must be avoided\n"
        "- SOLUTION: Use CONTENT SIGNALS to identify highlights tables (few rows, <80% total),\n"
        "  not page numbers. Only extract from the main SOI section.\n\n"
        "*** CRITICAL: DO NOT SKIP MAIN SOI ROWS (COMMON ERROR) ***\n"
        "A dangerous extraction pattern is:\n"
        "1. Model sees a security in the 'Top Holdings' summary (e.g., Page 2)\n"
        "2. Model later sees the SAME security in the Main SOI (e.g., Page 6)\n"
        "3. Model WRONGLY thinks: 'I already extracted this, skip it'\n"
        "4. Result: Main SOI row is missing, causing arithmetic mismatch\n\n"
        "THE CORRECT BEHAVIOR:\n"
        "- IGNORE all rows from summary/highlights tables (do not extract them)\n"
        "- EXTRACT ALL rows from the Main SOI (even if names appeared in summaries)\n"
        "- The Main SOI is the ONLY authoritative source for holdings\n"
        "- Summary tables exist for human readers, NOT for extraction\n\n"
        "EXAMPLE - Equity Fund with Top Holdings Summary:\n"
        "  Page 2: 'Top Holdings' shows 'Compania Cervecerias Unidas S.A., ADR' = $7.3M\n"
        "  Page 6: Main SOI shows 'Compania Cervecerias Unidas S.A., ADR' = $7,394,716\n"
        "  WRONG: Skip the Page 6 row because 'already saw it on Page 2'\n"
        "  CORRECT: Extract the Page 6 row (the Page 2 row was never extracted)\n\n"
        "*** NEVER USE 'Unknown Section' - ABSOLUTE PROHIBITION ***\n"
        "If you cannot determine the section_path for a holding:\n"
        "- DO NOT emit it with section_path = ['Unknown Section']\n"
        "- Instead, look harder for context: check page headers, preceding rows, '(continued)' markers\n"
        "- If still no context: SKIP the row entirely rather than use 'Unknown Section'\n"
        "'Unknown Section' WILL CAUSE EXTRACTION FAILURE. It must NEVER appear in output.\n\n"
        "COMMON CAUSES OF 'Unknown Section':\n"
        "1. You extracted from a Top Holdings table before the main SOI\n"
        "2. You missed a section header on a previous page\n"
        "3. Holdings appear after a 'Total Investments' row (these are likely recap data)\n"
        "If you find yourself wanting to use 'Unknown Section', STOP and re-examine what table you're in.\n\n"
        "*** ARITHMETIC SANITY CHECK FOR TOP HOLDINGS ***\n"
        "After extracting holdings, compare your sum to the Total row:\n"
        "- If Total row fair_value is 5x+ larger than sum of extracted holdings: YOU ARE IN A TOP HOLDINGS TABLE\n"
        "- If Total row shows ~20-40% but you only have 5-15 holdings: THIS IS A TOP HOLDINGS TABLE\n"
        "- DISCARD all rows from this table and find the main Schedule of Investments\n\n"
        "============================================================\n"
        "PRIORITY 5.6: STRATEGY ALLOCATION TABLES (DO NOT EXTRACT)\n"
        "============================================================\n\n"
        "*** CRITICAL: SKIP STRATEGY/ALLOCATION SUMMARY TABLES ***\n"
        "Many fund-of-funds documents include 'Investment Strategy' or 'Asset Allocation'\n"
        "summary tables that show how the fund allocates its investments by strategy.\n\n"
        "*** DETECTION: YOU ARE IN A STRATEGY ALLOCATION TABLE IF ***\n"
        "1. The table title mentions:\n"
        "   - 'Investment Strategy as a Percentage of Investments'\n"
        "   - 'Strategy Allocation' or 'Asset Allocation'\n"
        "   - 'Strategy Breakdown' or 'Investment Categories'\n"
        "2. Rows show strategy names with percentages that sum to ~100%:\n"
        "   - 'Convertible Arbitrage 8.11%'\n"
        "   - 'Credit Strategies 14.39%'\n"
        "   - 'Long/Short Equity 35.22%'\n"
        "   - 'Multi-Strategy 42.28%'\n"
        "   - Total = 100%\n"
        "3. These percentages represent 'portion of this fund's investments',\n"
        "   NOT 'percent of total net assets'\n\n"
        "*** RULE: DO NOT EXTRACT STRATEGY ALLOCATION ROWS ***\n"
        "These rows use a DIFFERENT DENOMINATOR than the main SOI:\n"
        "- Strategy allocation: % of THIS FUND'S investments (sums to 100%)\n"
        "- Main SOI: % of TOTAL NET ASSETS (may be <100% due to cash, liabilities)\n\n"
        "Extracting strategy allocation rows as SUBTOTAL causes arithmetic mismatches:\n"
        "- Holdings sum to X% of net assets\n"
        "- Strategy subtotal shows 100% (of investments)\n"
        "- Validator compares X% != 100% = ERROR\n\n"
        "*** ACTION: SKIP THESE TABLES ENTIRELY ***\n"
        "When you detect a strategy allocation table:\n"
        "- DO NOT emit any SUBTOTAL rows from this table\n"
        "- DO NOT emit any HOLDING rows from this table\n"
        "- Continue to the actual holdings list with individual securities\n\n"
        "============================================================\n"
        "PRIORITY 5.7: 100% SUBTOTAL DETECTION RULE\n"
        "============================================================\n\n"
        "*** RED FLAG: SUBTOTALS THAT SUM TO EXACTLY 100% ***\n"
        "If within a single fund/section, your SUBTOTAL rows sum to exactly 100%:\n"
        "- This indicates you're extracting INTERNAL ALLOCATION percentages\n"
        "- NOT percentages relative to total net assets\n\n"
        "EXAMPLE - WRONG EXTRACTION:\n"
        "  Fund: 'Aetos Capital Multi-Strategy Arbitrage Fund'\n"
        "  Extracted SUBTOTALs:\n"
        "    - Convertible Arbitrage: 8.11%\n"
        "    - Credit Strategies: 14.39%\n"
        "    - ... more strategies ...\n"
        "    - Total: 100.00%  <-- RED FLAG!\n\n"
        "  Meanwhile, individual holdings in this fund:\n"
        "    - Holding A: 2.1% of net assets\n"
        "    - Holding B: 1.8% of net assets\n"
        "    - Sum: ~50% of net assets  <-- DIFFERENT DENOMINATOR!\n\n"
        "*** RULE: IF SUBTOTALS SUM TO 100%, YOU'RE IN THE WRONG TABLE ***\n"
        "- The 100% is 'allocation within this sub-fund'\n"
        "- Individual holdings use 'percent of master fund net assets'\n"
        "- These are INCOMPATIBLE - do not mix them\n\n"
        "*** ACTION: SKIP 100% ALLOCATION SUBTOTALS ***\n"
        "If you see a section where strategy/category subtotals sum to 100%:\n"
        "- DO NOT emit these as SUBTOTAL rows\n"
        "- ONLY emit the individual HOLDING rows with their % of net assets values\n"
        "- The 100% allocation breakdown is metadata, not SOI data\n\n"
        "============================================================\n"
        "PRIORITY 5.8: FUND-OF-FUNDS DENOMINATOR CONSISTENCY\n"
        "============================================================\n\n"
        "*** CRITICAL: ALL PERCENTAGES MUST USE THE SAME DENOMINATOR ***\n"
        "In fund-of-funds structures, multiple percentage contexts exist:\n\n"
        "1. MASTER FUND LEVEL (EXTRACT THIS):\n"
        "   - Individual holding % = fair_value / master_fund_net_assets\n"
        "   - These are what we want in percent_net_assets_raw\n"
        "   - Example: 'Oceanwood Global Opportunities: $50M = 10.4% of net assets'\n\n"
        "2. SUB-FUND ALLOCATION LEVEL (DO NOT EXTRACT):\n"
        "   - Strategy % = strategy_allocation / sub_fund_total\n"
        "   - These sum to 100% within each sub-fund\n"
        "   - Example: 'Long/Short Equity strategy: 35% of this sub-fund's investments'\n\n"
        "*** RULE: NEVER MIX DENOMINATORS ***\n"
        "If a document shows both:\n"
        "- 'Credit Strategies 14.39%' (sub-fund allocation, sums to 100%)\n"
        "- 'Cadmus Capital Partners 0.3%' (holding % of master net assets)\n\n"
        "Only extract the HOLDING-level percentages (0.3%).\n"
        "Do NOT extract the sub-fund allocation percentages (14.39%).\n\n"
        "*** DETECTION HEURISTIC ***\n"
        "Look at the column header:\n"
        "- '% of Net Assets' or '% Net Assets': EXTRACT (master fund level)\n"
        "- '% of Investments' or 'Percentage of Investments': SKIP (internal allocation)\n"
        "- 'Strategy Allocation %': SKIP (internal allocation)\n\n"
        "============================================================\n"
        "PRIORITY 5.9: DIVERSIFICATION/INDUSTRY SUMMARY TABLES (DO NOT EXTRACT)\n"
        "============================================================\n\n"
        "*** CRITICAL: SKIP 'DIVERSIFICATION OF ASSETS' AND SIMILAR TABLES ***\n"
        "Many N-CSR documents include summary tables that show portfolio diversification\n"
        "by industry or sector. These appear BEFORE the main Schedule of Investments.\n\n"
        "*** BLACKLISTED TABLE TITLES - SKIP ENTIRELY ***\n"
        "If you see a table with any of these titles, DO NOT extract from it:\n"
        "- 'DIVERSIFICATION OF ASSETS'\n"
        "- 'Diversification of Assets'\n"
        "- 'MAJOR INDUSTRY EXPOSURE'\n"
        "- 'Major Industry Exposure'\n"
        "- 'Industry Diversification'\n"
        "- 'Sector Diversification'\n"
        "- 'Asset Diversification'\n"
        "- 'Portfolio Diversification'\n"
        "- 'Investment Diversification'\n\n"
        "*** DETECTION: YOU ARE IN A DIVERSIFICATION SUMMARY TABLE IF ***\n"
        "1. The table has a title matching any blacklisted title above\n"
        "2. Rows show ONLY industry/sector names with Cost, Value, and % columns\n"
        "   - Example: 'Aerospace and Defense ... $6,809,521 ... $6,295,382 ... 5.0%'\n"
        "3. There are NO individual company/security names - just category aggregates\n"
        "4. The table has a 'Total Investments' row at the bottom\n"
        "5. All percentages in the table sum to ~100%\n\n"
        "*** WHY THESE TABLES CAUSE ERRORS ***\n"
        "If you extract from a Diversification table:\n"
        "- You'll emit SUBTOTAL rows for each industry (Aerospace, Banking, etc.)\n"
        "- But there are NO HOLDING rows underneath them (no individual securities)\n"
        "- The validator will see SUBTOTALs with no children = ORPHANED_TOTAL errors\n"
        "- The section path 'Diversification of Assets > Aerospace' is WRONG\n"
        "- The correct path is 'CONVERTIBLE BONDS > Aerospace' from the main SOI\n\n"
        "*** RULE: SKIP DIVERSIFICATION TABLES ENTIRELY ***\n"
        "When you detect a Diversification of Assets table:\n"
        "- DO NOT emit any HOLDING rows from this table\n"
        "- DO NOT emit any SUBTOTAL rows from this table\n"
        "- DO NOT emit any TOTAL rows from this table\n"
        "- Continue scanning until you find the main 'Portfolio of Investments' or\n"
        "  'Schedule of Investments' section with actual individual securities\n\n"
        "*** THE MAIN SOI HAS INDIVIDUAL SECURITIES ***\n"
        "The correct table to extract from shows:\n"
        "- Individual company names: 'AAR Corp.', 'Alliant Techsystems Inc.', etc.\n"
        "- Bond details: '$1,500,000 AAR Corp. 1.75% 2026 cv. sr. notes (BB)'\n"
        "- NOT just category summaries like 'Aerospace and Defense ... 5.0%'\n\n"
        "============================================================\n"
        "PRIORITY 6: SECTION PATH HIERARCHY AND RESET\n"
        "============================================================\n\n"
        "*** SECTION PATH MUST RESET AT NEW MAJOR SECTIONS ***\n"
        "When you encounter a new ASSET CLASS header (e.g., 'MANDATORY CONVERTIBLE SECURITIES'):\n"
        "- COMPLETELY RESET section_path to just that new header\n"
        "- DO NOT carry over industry sub-categories from the previous section\n\n"
        "EXAMPLE - WRONG:\n"
        "  Previous section: ['CONVERTIBLE PREFERRED STOCKS', 'AUTOMOTIVE']\n"
        "  New header: 'MANDATORY CONVERTIBLE SECURITIES -- 18.9%'\n"
        "  WRONG path: ['CONVERTIBLE PREFERRED STOCKS', 'AUTOMOTIVE', 'MANDATORY CONVERTIBLE SECURITIES']\n\n"
        "EXAMPLE - CORRECT:\n"
        "  New header: 'MANDATORY CONVERTIBLE SECURITIES -- 18.9%'\n"
        "  CORRECT path: ['MANDATORY CONVERTIBLE SECURITIES']\n\n"
        "*** SANITY CHECK: SUBTOTAL CANNOT EXCEED SECTION TOTAL ***\n"
        "If an industry subtotal (e.g., 'AUTOMOTIVE') has a fair_value larger than the section's\n"
        "'TOTAL [SECTION]' row, something is WRONG. This usually means:\n"
        "- Holdings from multiple sections got merged under one industry name\n"
        "- Section path was not properly reset between major asset classes\n"
        "Re-check your section_path assignments when this occurs.\n\n"
        "============================================================\n"
        "PRIORITY 7: SUBTOTAL PATH MIRROR RULE (CRITICAL)\n"
        "============================================================\n\n"
        "*** THE LABEL MUST APPEAR IN THE PATH (SUBTOTALS ONLY) ***\n"
        "For every SUBTOTAL row, the 'label' value MUST appear as the LAST element of 'section_path'.\n"
        "This is a strict validation rule for SUBTOTALS.\n\n"
        "MIRROR RULE: section_path[-1] == label (case-insensitive match)\n\n"
        "*** EXCEPTION: TOTAL ROWS ***\n"
        "Do NOT apply the Mirror Rule to TOTAL rows (rows starting with 'Total', 'Net Assets').\n"
        "- TOTAL rows share the PARENT path.\n"
        "- They do NOT create a new path level.\n"
        "- Example: Label='Total Muni Bonds', Path=['Muni Bonds'] (NOT ['Muni Bonds', 'Total Muni Bonds'])\n\n"
        "*** EXAMPLES OF CORRECT vs WRONG ***\n\n"
        "Document shows: 'AUTOMOTIVE -- 0.8%' under 'CONVERTIBLE PREFERRED STOCKS'\n\n"
        "CORRECT:\n"
        "  {row_type: 'SUBTOTAL', section_path: ['CONVERTIBLE PREFERRED STOCKS', 'AUTOMOTIVE'], label: 'AUTOMOTIVE'}\n"
        "  ✓ section_path ends with 'AUTOMOTIVE', matches label\n\n"
        "WRONG:\n"
        "  {row_type: 'SUBTOTAL', section_path: ['CONVERTIBLE PREFERRED STOCKS'], label: 'AUTOMOTIVE'}\n"
        "  ✗ section_path does NOT include 'AUTOMOTIVE' - THIS CAUSES VALIDATION FAILURE\n"
        "  ✗ Validator will sum ALL holdings under 'CONVERTIBLE PREFERRED STOCKS' (~$23M)\n"
        "  ✗ But the AUTOMOTIVE subtotal is only ~$942K, creating a huge mismatch\n\n"
        "*** SELF-CHECK BEFORE EMITTING ANY SUBTOTAL ***\n"
        "Ask yourself: Does section_path end with the same value as label?\n"
        "- If YES: emit the row\n"
        "- If NO: FIX section_path to include label as the last element\n\n"
        "*** EMIT A SUBTOTAL FOR EACH INDUSTRY HEADER ***\n"
        "When a section has multiple industry headers (AUTOMOTIVE, BANKING, ENERGY, etc.):\n"
        "- Emit a separate SUBTOTAL row for EACH industry\n"
        "- Each SUBTOTAL must have section_path ending with that industry name\n"
        "- Do NOT emit just one SUBTOTAL for the first industry and skip the rest\n\n"
        "EXAMPLE - Section 'CONVERTIBLE PREFERRED STOCKS' with 7 industries:\n"
        "  {section_path: ['CONVERTIBLE PREFERRED STOCKS', 'AUTOMOTIVE'], label: 'AUTOMOTIVE', ...}\n"
        "  {section_path: ['CONVERTIBLE PREFERRED STOCKS', 'BANKING/SAVINGS AND LOAN'], label: 'BANKING/SAVINGS AND LOAN', ...}\n"
        "  {section_path: ['CONVERTIBLE PREFERRED STOCKS', 'ENERGY'], label: 'ENERGY', ...}\n"
        "  {section_path: ['CONVERTIBLE PREFERRED STOCKS', 'ENTERTAINMENT'], label: 'ENTERTAINMENT', ...}\n"
        "  {section_path: ['CONVERTIBLE PREFERRED STOCKS', 'FINANCIAL AND INSURANCE'], label: 'FINANCIAL AND INSURANCE', ...}\n"
        "  {section_path: ['CONVERTIBLE PREFERRED STOCKS', 'HEALTH CARE'], label: 'HEALTH CARE', ...}\n"
        "  {section_path: ['CONVERTIBLE PREFERRED STOCKS', 'MINING'], label: 'MINING', ...}\n\n"
        "If you only emit AUTOMOTIVE and skip the others, holdings under BANKING, ENERGY, etc. will\n"
        "have no matching SUBTOTAL, causing MISSING_SUBTOTAL warnings.\n\n"
        "============================================================\n"
        "STRUCTURE AND LAYOUT\n"
        "============================================================\n\n"
        "*** SECTION CONTINUITY ACROSS PAGES ***\n"
        "- section_path from page N continues on page N+1 until a NEW section heading appears\n"
        "- Column headers repeated at page top do NOT change section_path\n"
        "- A section ENDS only when you see its TOTAL row or a new section header\n\n"
        "*** MERGE SPLIT SECTIONS (CRITICAL) ***\n"
        "If a section like 'Long-Term Municipal Bonds' spans multiple pages:\n"
        "1. It is ONE logical section.\n"
        "2. Do NOT create a new/duplicate section object for the continuation.\n"
        "3. If the first part is in ['MUNICIPAL BONDS', 'Long-Term Municipal Bonds'], the continuation MUST use the SAME path.\n"
        "4. Do NOT drop the parent 'MUNICIPAL BONDS' from the path on the second page.\n"
        "5. Inconsistent paths cause the Total row to disconnect from the holdings.\n\n"
        "*** ORPHANED ROWS AT PAGE BOUNDARIES (CRITICAL) ***\n"
        "Rows at the top/bottom of pages are often separated by headers/footers.\n"
        "- ALWAYS extract rows even if they are visually separated.\n"
        "- A row starting with parentheses, e.g., '(San Diego Gas)...', is a VALID HOLDING.\n"
        "- Ignore intervening headers like 'ALLIANCE NATIONAL...' or 'Portfolio of Investments' when connecting rows.\n"
        "- Pay special attention to the FIRST row on a new page and the LAST row on a previous page.\n\n"
        "*** CRITICAL: SUBTOTAL ROWS MUST USE THE INNER SECTION PATH ***\n"
        "When you see an industry/category header like 'Advertising -- 0.9%' within a section:\n"
        "1. FIRST update section_path to INCLUDE the new category\n"
        "2. THEN emit the SUBTOTAL row using that UPDATED path\n"
        "3. THEN emit all HOLDING rows under that path\n\n"
        "EXAMPLE - Document shows:\n"
        "  CONVERTIBLE BONDS AND NOTES -- 53.6%\n"
        "    Advertising -- 0.9%\n"
        "      $1,000,000 Lamar Advertising 2.875% 2010 ... $1,078,125\n"
        "    Aerospace and Defense -- 1.2%\n"
        "      $1,500,000 Goldman Sachs 1% 2009 ... $1,438,740\n"
        "  TOTAL CONVERTIBLE BONDS AND NOTES ... $61,987,411\n\n"
        "CORRECT extraction:\n"
        "  {row_type: 'SUBTOTAL', section_path: ['CONVERTIBLE BONDS AND NOTES', 'Advertising'], label: 'Advertising', percent_net_assets_raw: '0.9%'}\n"
        "  {row_type: 'HOLDING', section_path: ['CONVERTIBLE BONDS AND NOTES', 'Advertising'], investment: 'Lamar Advertising...', fair_value_raw: '$1,078,125'}\n"
        "  {row_type: 'SUBTOTAL', section_path: ['CONVERTIBLE BONDS AND NOTES', 'Aerospace and Defense'], label: 'Aerospace and Defense', percent_net_assets_raw: '1.2%'}\n"
        "  {row_type: 'HOLDING', section_path: ['CONVERTIBLE BONDS AND NOTES', 'Aerospace and Defense'], investment: 'Goldman Sachs...', fair_value_raw: '$1,438,740'}\n"
        "  {row_type: 'TOTAL', section_path: ['CONVERTIBLE BONDS AND NOTES'], label: 'TOTAL CONVERTIBLE BONDS AND NOTES', fair_value_raw: '$61,987,411'}\n\n"
        "WRONG extraction (causes validation failures):\n"
        "  {row_type: 'SUBTOTAL', section_path: ['CONVERTIBLE BONDS AND NOTES'], label: 'Advertising', ...}  <-- WRONG! Missing 'Advertising' in path\n"
        "  {row_type: 'HOLDING', section_path: ['CONVERTIBLE BONDS AND NOTES'], investment: 'Lamar...'}  <-- WRONG! Missing industry in path\n\n"
        "The SUBTOTAL's section_path MUST include the category it summarizes, not just the parent.\n\n"
        "*** SUMMARY/INDUSTRY EXPOSURE TABLES ***\n"
        "Tables listing industry allocations (e.g., 'Pharmaceuticals 11.7%', 'Technology 11.2%'):\n"
        "- Each category line is a SUBTOTAL (not HOLDING)\n"
        "- The 'Total' line is a TOTAL row\n"
        "- These are separate from detailed holdings\n\n"
        "*** OTHER RULES ***\n"
        "- Combine multi-line issuer + tranche descriptions into single HOLDING\n"
        "- Preserve numbers exactly as printed in *_raw fields (parentheses for negatives, currency codes)\n"
        "- When a column is absent, set the field to null\n\n"
        "============================================================\n"
        "PRIORITY 7.5: SINGLE-CATEGORY SECTIONS (CRITICAL)\n"
        "============================================================\n\n"
        "*** RULE: CAPTURE ASSET CLASS PERCENTAGE IF NO SUB-CATEGORIES EXIST ***\n"
        "If an Asset Class header has a percentage (e.g. 'SHORT-TERM INVESTMENTS -- 2.14%')\n"
        "and you do NOT see breakdown industry headers (like 'Advertising -- 0.9%') below it:\n"
        "1. Treat the Asset Class itself as the Category/Industry.\n"
        "2. Emit a SUBTOTAL row for the Asset Class header.\n"
        "   - label: 'SHORT-TERM INVESTMENTS' (The Asset Class Name)\n"
        "   - percent_net_assets_raw: '2.14%' (from the header)\n"
        "   - section_path: [..., 'SHORT-TERM INVESTMENTS']\n"
        "3. Emit all holdings under this path.\n"
        "   - section_path: [..., 'SHORT-TERM INVESTMENTS']\n\n"
        "*** WHY: WITHOUT THIS SUBTOTAL, THE PERCENTAGE IS LOST ***\n"
        "If you only emit HOLDING rows and a TOTAL row, but no SUBTOTAL row with the percentage:\n"
        "- The validator sums the percentages of sub-categories.\n"
        "- If there are no sub-categories, the sum is 0%.\n"
        "- 0% != 2.14% -> TOTAL_MISMATCH_PCT error.\n"
        "So you MUST emit a SUBTOTAL row to 'carry' the percentage for the section.\n\n"
        "*** EXAMPLE: SHORT-TERM INVESTMENTS WITH NO SUB-CATEGORIES ***\n"
        "Document shows:\n"
        "  SHORT-TERM INVESTMENTS -- 2.14%\n"
        "    Variable Rate Demand Notes\n"
        "      Minneapolis, Minnesota ... $300,000\n"
        "      Rochester, Minnesota ... $250,000\n"
        "    -----------\n"
        "    550,000\n"
        "  TOTAL SHORT-TERM INVESTMENTS ... $550,000 ... 2.14%\n\n"
        "CORRECT extraction:\n"
        "  {row_type: 'SUBTOTAL', section_path: ['FUND_NAME', 'SHORT-TERM INVESTMENTS'], label: 'SHORT-TERM INVESTMENTS', percent_net_assets_raw: '2.14%'}\n"
        "  {row_type: 'HOLDING', section_path: ['FUND_NAME', 'SHORT-TERM INVESTMENTS'], investment: 'Minneapolis, Minnesota...', fair_value_raw: '$300,000'}\n"
        "  {row_type: 'HOLDING', section_path: ['FUND_NAME', 'SHORT-TERM INVESTMENTS'], investment: 'Rochester, Minnesota...', fair_value_raw: '$250,000'}\n"
        "  {row_type: 'TOTAL', section_path: ['FUND_NAME', 'SHORT-TERM INVESTMENTS'], label: 'TOTAL SHORT-TERM INVESTMENTS', fair_value_raw: '$550,000', percent_net_assets_raw: '2.14%'}\n\n"
        "WRONG extraction (causes TOTAL_MISMATCH_PCT):\n"
        "  {row_type: 'HOLDING', section_path: ['FUND_NAME', 'SHORT-TERM INVESTMENTS', 'Variable Rate Demand Notes'], ...}  <-- No SUBTOTAL with percentage!\n"
        "  {row_type: 'TOTAL', ...}  <-- Validator sees 0% calculated vs 2.14% extracted\n\n"
        "============================================================\n"
        "PRIORITY 8: SUBTOTAL EMISSION TIMING (CRITICAL)\n"
        "============================================================\n\n"
        "*** STATE MACHINE FOR SECTION TRANSITIONS ***\n\n"
        "The SUBTOTAL row's numeric values (fair_value_raw, cost_raw) come from the section's\n"
        "SUMMARY LINE, which typically appears AFTER all holdings in that section.\n\n"
        "DOCUMENT LAYOUT (typical):\n"
        "  Industry Header: 'Advertising -- 0.9%'\n"
        "  [Holdings for Advertising]\n"
        "  Summary Line: '                           1,078,125    1,050,000' <- Advertising's totals!\n"
        "  Industry Header: 'Aerospace -- 1.2%' <- Next section starts here\n"
        "  [Holdings for Aerospace]\n"
        "  Summary Line: '                           1,438,740    1,400,000' <- Aerospace's totals!\n\n"
        "*** CRITICAL RULE: SUBTOTAL VALUES BELONG TO THEIR OWN SECTION ***\n\n"
        "When you encounter a summary line with aggregated values:\n"
        "1. Those values belong to the CURRENT industry section (the one you just finished)\n"
        "2. NOT to the NEXT industry section (which hasn't started yet)\n"
        "3. The section_path for this SUBTOTAL must match the holdings above it\n\n"
        "*** COMMON ERROR - OFF-BY-ONE ATTRIBUTION ***\n\n"
        "WRONG (causes cascading arithmetic errors):\n"
        "  See 'Advertising -- 0.9%' header\n"
        "  Emit HOLDING rows with path [..., 'Advertising']\n"
        "  See summary line '1,078,125'\n"
        "  See NEXT header 'Aerospace -- 1.2%'\n"
        "  Update section_path to [..., 'Aerospace']\n"
        "  Emit SUBTOTAL with path [..., 'Aerospace'], fair_value='1,078,125'  <-- WRONG!\n"
        "  (Advertising's values are now attributed to Aerospace!)\n\n"
        "CORRECT:\n"
        "  See 'Advertising -- 0.9%' header\n"
        "  Update section_path to [..., 'Advertising']\n"
        "  Emit SUBTOTAL with path [..., 'Advertising'], percent='0.9%' (from header)\n"
        "  Emit HOLDING rows with path [..., 'Advertising']\n"
        "  See summary line '1,078,125' <- This is Advertising's fair_value!\n"
        "  Update the Advertising SUBTOTAL's fair_value_raw to '1,078,125'\n"
        "  See 'Aerospace -- 1.2%' header\n"
        "  Update section_path to [..., 'Aerospace']\n"
        "  Emit SUBTOTAL with path [..., 'Aerospace'], percent='1.2%'\n"
        "  ... continue pattern ...\n\n"
        "*** SELF-CHECK: VERIFY SUBTOTAL VALUES MATCH THEIR HOLDINGS ***\n"
        "Before emitting a SUBTOTAL, verify:\n"
        "1. The section_path matches the holdings directly above\n"
        "2. The fair_value_raw is the sum of those holdings' fair values (if shown)\n"
        "3. If the values don't match, you may have shifted attribution by one section\n\n"
        "============================================================\n"
        "*** FINAL CHECK: IS THIS A SUMMARY TABLE? (CRITICAL) ***\n"
        "============================================================\n\n"
        "Before outputting ANY table, perform this sanity check on its TOTAL row:\n\n"
        "IF BOTH of these conditions are true:\n"
        "  1. The TOTAL row's 'percent_net_assets_raw' is LESS THAN 80% (e.g., 22%, 35%, 54%)\n"
        "  2. AND the table has FEWER THAN 20 holdings\n\n"
        "THEN: THIS IS A SUMMARY/TOP HOLDINGS TABLE. DO NOT EXTRACT IT.\n"
        "  -> Output NOTHING for this table.\n"
        "  -> Continue scanning for the MAIN Schedule of Investments.\n"
        "  -> The Main SOI will have a Total showing 90-160% of net assets.\n\n"
        "EXAMPLE OF WHAT TO REJECT:\n"
        "  Table: 'Top 10 Holdings'\n"
        "  Holdings: 10 rows\n"
        "  Total: 'Total Top Holdings ... 35.2%'\n"
        "  -> 35.2% < 80% AND 10 < 20 holdings -> REJECT ENTIRE TABLE.\n\n"
        "EXAMPLE OF WHAT TO KEEP:\n"
        "  Table: 'Schedule of Investments'\n"
        "  Holdings: 150 rows\n"
        "  Total: 'Total Investments ... 98.5%'\n"
        "  -> 98.5% > 80% -> THIS IS THE MAIN SOI. EXTRACT IT.\n\n"
        "This check MUST be performed. Missing it causes double-counting errors.\n\n"
        "############################################################\n"
        "############################################################\n"
        "*** COMPLETENESS SELF-CHECK (MANDATORY BEFORE TOTAL) ***\n"
        "############################################################\n"
        "############################################################\n\n"
        "Before emitting ANY 'TOTAL INVESTMENTS' row, you MUST verify:\n"
        "  calculated_sum = sum(all HOLDING fair_values you extracted)\n"
        "  extracted_total = TOTAL row's fair_value from the document\n"
        "  extraction_ratio = calculated_sum / extracted_total\n\n"
        "*** EXTRACTION RATIO VALIDATION (CRITICAL) ***\n"
        "The extraction_ratio tells you if your extraction is complete:\n\n"
        "  ratio >= 0.90 (90%+): GOOD - Proceed with TOTAL emission\n"
        "  ratio 0.50-0.89 (50-89%): WARNING - Missing holdings, re-scan pages\n"
        "  ratio 0.10-0.49 (10-49%): SEVERE - Major extraction failure\n"
        "  ratio < 0.10 (<10%): CRITICAL - Nearly complete failure\n"
        "  ratio > 1.10 (>110%): ERROR - Duplicate holdings or multi-fund mixing\n\n"
        "*** CHECK 1 - UNDERCOUNT DETECTION (CRITICAL) ***\n"
        "If calculated_sum < 0.9 * extracted_total (you captured <90% of holdings):\n"
        "  -> You MISSED holdings. STOP and re-scan all pages.\n"
        "  -> Look for continuation pages you may have skipped.\n"
        "  -> Check for sections without headers that continue previous pages.\n"
        "  -> A large gap (>$10M) means you likely skipped entire pages or sections.\n"
        "  -> DO NOT emit the TOTAL row until you find the missing holdings.\n\n"
        "*** CHECK 2 - OVERCOUNT DETECTION ***\n"
        "If calculated_sum > 1.1 * extracted_total (you captured >110% of expected):\n"
        "  -> You have DUPLICATE holdings or extracted from multiple funds.\n"
        "  -> Check section_paths for fund name consistency.\n"
        "  -> Ensure you didn't extract from both a Summary table AND the main SOI.\n"
        "  -> If this is a multi-fund document, verify each holding has the correct fund in section_path.\n\n"
        "*** CHECK 3 - SEVERE UNDERCOUNT (CRITICAL ERROR) ***\n"
        "If calculated_sum < 0.5 * extracted_total (you captured <50% of holdings):\n"
        "  -> CRITICAL: You missed MOST of the holdings. This is a severe extraction failure.\n"
        "  -> Re-examine the document structure. You may have:\n"
        "     - Skipped entire pages of holdings\n"
        "     - Stopped extraction too early\n"
        "     - Missed continuation pages\n"
        "     - Only extracted from one fund in a multi-fund document\n"
        "  -> The TOTAL row you're seeing may belong to a different fund/section.\n\n"
        "*** RATIO EXAMPLES ***\n"
        "  TOTAL shows $100,000,000. Your holdings sum to:\n"
        "  - $95,000,000 (95%) -> OK, within tolerance\n"
        "  - $70,000,000 (70%) -> WARNING: Missing ~$30M of holdings, re-scan\n"
        "  - $50,000,000 (50%) -> CRITICAL: Missing half the portfolio\n"
        "  - $10,000,000 (10%) -> SEVERE: You only extracted 10% - major failure\n"
        "  - $200,000,000 (200%) -> ERROR: Duplicate holdings detected\n\n"
        "*** MULTI-FUND EXTRACTION RATIO CHECK ***\n"
        "For multi-fund documents, perform this check PER FUND:\n"
        "1. Group all holdings by the FIRST element of section_path (fund name)\n"
        "2. For each fund, sum the holdings' fair_values\n"
        "3. Compare to that fund's TOTAL INVESTMENTS row\n"
        "4. If ANY fund has ratio < 0.9, you missed holdings for that fund\n"
        "5. If ANY fund has ratio > 1.1, you have duplicate holdings or cross-fund mixing\n\n"
        "Output must reflect only what appears in the document. Be precise and thorough."
    )

    schema: Dict[str, Any] = {
        "type": "object",
        "properties": {
            "soi_title": {
                "type": ["string", "null"],
                "description": (
                    "Exact schedule title if present (e.g., 'Schedule of Investments', "
                    "'Portfolio of Investments', including 'Consolidated'/'Condensed')."
                ),
            },
            "as_of_date": {
                "type": ["string", "null"],
                "description": (
                    "As-of date for the schedule if present (e.g., 'December 31, 2024')."
                ),
            },
            "reporting_basis": {
                "type": ["string", "null"],
                "description": "If present, e.g., 'Unaudited' or 'Audited'.",
            },
            "soi_rows": {
                "type": "array",
                "description": (
                    "All SOI line items across all pages: holdings + subtotals + totals. "
                    "Each object is one line item from the schedule. "
                    "IMPORTANT: Use the correct row_type and ensure HOLDING rows have "
                    "a real security name in 'investment', not column headers."
                ),
                "items": {
                    "oneOf": [
                        # HOLDING row schema
                        {
                            "type": "object",
                            "description": (
                                "A HOLDING row represents an individual investment/security. "
                                "MUST have a real security name (not column headers like "
                                "'Principal Amount' or 'Value')."
                            ),
                            "properties": {
                                "row_type": {
                                    "type": "string",
                                    "const": "HOLDING",
                                    "description": "Must be 'HOLDING' for investment rows.",
                                },
                                "section_path": {
                                    "type": ["array", "null"],
                                    "items": {"type": "string"},
                                    "description": "Hierarchy of headings (asset class/sector).",
                                },
                                "investment": {
                                    "type": "string",
                                    "minLength": 1,
                                    "description": (
                                        "REQUIRED: The security/investment name. MUST be an identifiable "
                                        "issuer, company, fund, or bond description (e.g., 'Apple Inc.', "
                                        "'Kerr-McGee Corp. 5.25% 2010 cv. sub. deb.', 'U.S. Treasury Notes'). "
                                        "BLACKLISTED VALUES (never use): 'Principal Amount', 'Principal Amount:', "
                                        "'Value', 'Value (Note 1)', 'Value (Note 1):', 'Shares', 'Cost', 'Fair Value', "
                                        "'Par Amount', 'Par Value', 'Units', 'Notional', 'Rate', 'Maturity'. "
                                        "NUMERIC REJECTION: If the value is primarily numeric (e.g., '$1,500,000', "
                                        "'8,169,847'), it is NOT a valid investment name - look above or on the "
                                        "previous page for the actual security name. "
                                        "If the investment name matches any blacklisted value or is numeric-only, "
                                        "DO NOT emit the row."
                                    ),
                                },
                                "label": {
                                    "type": "null",
                                    "description": "Must be null for HOLDING rows.",
                                },
                                "instrument_type": {
                                    "type": ["string", "null"],
                                    "description": "e.g., common stock, preferred, CLO tranche.",
                                },
                                "quantity_raw": {
                                    "type": ["string", "null"],
                                    "description": "Shares/units/principal as printed.",
                                },
                                "quantity_type": {
                                    "type": ["string", "null"],
                                    "enum": ["shares", "principal", "par", "units", "notional", "contracts", "other", "unknown", None],
                                },
                                "cost_raw": {"type": ["string", "null"]},
                                "amortized_cost_raw": {"type": ["string", "null"]},
                                "fair_value_raw": {"type": ["string", "null"]},
                                "percent_net_assets_raw": {
                                    "type": ["string", "null"],
                                    "description": (
                                        "Percentage of net assets. MUST include '%' sign. "
                                        "PRESERVE the value exactly as printed (e.g., '2.78%' stays '2.78%'). "
                                        "PARENTHESES RULE: If fair_value_raw is POSITIVE but percent has parentheses, "
                                        "REMOVE the parentheses. Example: '(1.59%)' with positive FV -> '1.59%'. "
                                        "Output must NOT contain '(' or ')' when fair_value is positive."
                                    ),
                                },
                                "interest_rate_raw": {"type": ["string", "null"]},
                                "maturity_date": {"type": ["string", "null"]},
                                "currency_raw": {"type": ["string", "null"]},
                                "fair_value_level_raw": {"type": ["string", "null"]},
                                "footnote_markers": {"type": ["array", "null"], "items": {"type": "string"}},
                                "additional_fields": {
                                    "type": ["array", "null"],
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "column_header": {"type": "string"},
                                            "value_raw": {"type": "string"},
                                        },
                                        "required": ["column_header", "value_raw"],
                                    },
                                },
                                "row_text": {"type": ["string", "null"]},
                            },
                            "required": ["row_type", "investment"],
                        },
                        # SUBTOTAL row schema
                        {
                            "type": "object",
                            "description": (
                                "A SUBTOTAL row summarizes a group of holdings (e.g., sector subtotal). "
                                "Has aggregated values but no individual security name."
                            ),
                            "properties": {
                                "row_type": {
                                    "type": "string",
                                    "const": "SUBTOTAL",
                                    "description": "Must be 'SUBTOTAL' for subtotal rows.",
                                },
                                "section_path": {
                                    "type": ["array", "null"],
                                    "items": {"type": "string"},
                                },
                                "label": {
                                    "type": "string",
                                    "minLength": 1,
                                    "description": "REQUIRED: The subtotal label as shown.",
                                },
                                "investment": {
                                    "type": "null",
                                    "description": "Must be null for SUBTOTAL rows.",
                                },
                                "quantity_raw": {"type": ["string", "null"]},
                                "cost_raw": {"type": ["string", "null"]},
                                "amortized_cost_raw": {"type": ["string", "null"]},
                                "fair_value_raw": {"type": ["string", "null"]},
                                "percent_net_assets_raw": {
                                    "type": ["string", "null"],
                                    "description": (
                                        "Percentage of net assets. MUST include '%' sign. "
                                        "PRESERVE the value exactly as printed (e.g., '2.78%' stays '2.78%'). "
                                        "PARENTHESES RULE: If fair_value_raw is POSITIVE but percent has parentheses, "
                                        "REMOVE the parentheses. Output must NOT contain '(' or ')' when fair_value is positive."
                                    ),
                                },
                                "footnote_markers": {"type": ["array", "null"], "items": {"type": "string"}},
                                "row_text": {"type": ["string", "null"]},
                            },
                            "required": ["row_type", "label"],
                        },
                        # TOTAL row schema
                        {
                            "type": "object",
                            "description": (
                                "A TOTAL row represents grand totals (e.g., 'Total Investments'). "
                                "Has aggregated values for the entire schedule or major section."
                            ),
                            "properties": {
                                "row_type": {
                                    "type": "string",
                                    "const": "TOTAL",
                                    "description": "Must be 'TOTAL' for grand total rows.",
                                },
                                "section_path": {
                                    "type": ["array", "null"],
                                    "items": {"type": "string"},
                                },
                                "label": {
                                    "type": "string",
                                    "minLength": 1,
                                    "description": "REQUIRED: The total label (e.g., 'Total Investments').",
                                },
                                "investment": {
                                    "type": "null",
                                    "description": "Must be null for TOTAL rows.",
                                },
                                "quantity_raw": {"type": ["string", "null"]},
                                "cost_raw": {"type": ["string", "null"]},
                                "amortized_cost_raw": {"type": ["string", "null"]},
                                "fair_value_raw": {"type": ["string", "null"]},
                                "percent_net_assets_raw": {
                                    "type": ["string", "null"],
                                    "description": (
                                        "Percentage of net assets. MUST include '%' sign. "
                                        "PRESERVE the value exactly as printed (e.g., '92.45%' stays '92.45%'). "
                                        "PARENTHESES RULE: If fair_value_raw is POSITIVE but percent has parentheses, "
                                        "REMOVE the parentheses. Output must NOT contain '(' or ')' when fair_value is positive."
                                    ),
                                },
                                "footnote_markers": {"type": ["array", "null"], "items": {"type": "string"}},
                                "row_text": {"type": ["string", "null"]},
                            },
                            "required": ["row_type", "label"],
                        },
                    ],
                },
            },
        },
        "required": ["soi_rows"],
    }

    return {
        "input": remote_input,
        "parsing": parsing_config,
        "instructions": {
            "system_prompt": system_prompt,
            "schema": schema,
        },
        "settings": {
            "force_url_result": True,
            "array_extract": True,
            "citations": {"enabled": True, "numerical_confidence": True},
            "include_images": False,
            "optimize_for_latency": False,
        },
    }
